/*
 * bz_quest_vk_wc3.c - see bz_quest_vk_wc3.h.
 *
 * Every VkResult this file checks is compared explicitly against
 * VK_SUCCESS - there is no "assume success" path, per AGENTS.md.
 *
 * -- Blend mode -> Vulkan mapping evidence (do not change without
 * re-deriving) --
 * games/warcraft-3/renderer/mdx/r_mdx_geoset.c's MDLX_SetBlendMode() is the
 * desktop engine's own OpenGL mapping for every bzTTBlendMode_t value; this
 * file's blend_state_for_mode() below reproduces it 1:1 in Vulkan terms
 * (glBlendFunc(src,dst) with no glBlendFuncSeparate call maps to identical
 * color/alpha blend factors - see that function's per-case comments):
 *
 *   BZ_TTA_BLEND_OPAQUE (glBlendFunc(ONE,ZERO), depthMask ON)       -> no blend, depth write on
 *   BZ_TTA_BLEND_TRANSPARENT (alpha-key: glBlendFunc(ONE,ZERO), depthMask ON,
 *     uAlphaCutoff 0.5 - renderer/r_shader.c:308)                  -> no blend, depth write on, shader alpha-discard@0.5
 *   BZ_TTA_BLEND_ALPHA (glBlendFunc(SRC_ALPHA,ONE_MINUS_SRC_ALPHA), depthMask OFF)
 *   BZ_TTA_BLEND_ADDITIVE (glBlendFunc(ONE,ONE), depthMask OFF)
 *   BZ_TTA_BLEND_ADD_ALPHA (glBlendFunc(SRC_ALPHA,ONE), depthMask OFF)
 *   BZ_TTA_BLEND_MODULATE (glBlendFunc(DST_COLOR,ZERO), depthMask OFF)
 *   BZ_TTA_BLEND_MODULATE_2X (glBlendFunc(DST_COLOR,SRC_COLOR), depthMask OFF)
 *
 * MDLX_IsBlendedLayer() (r_mdx_geoset.c:220-222) treats every blend mode
 * >= BZ_TTA_BLEND_ALPHA (2) as needing a back-to-front-sorted "blended
 * pass", drawn after every OPAQUE/TRANSPARENT layer - this file's draw loop
 * reproduces that exact two-pass split (see
 * bz_quest_vk_wc3_render_target()'s doc comment below).
 *
 * MDLX_ApplyLayerFlags() (r_mdx_geoset.c:208-218) is the source for this
 * file's cull/depth-test/depth-write flag handling: MODEL_GEO_TWOSIDED
 * disables culling, MODEL_GEO_NO_DEPTH_TEST disables the depth test,
 * MODEL_GEO_NO_DEPTH_SET forces depth-write off (only ever an additional
 * override, never a way to force depth-write back on over a blended mode's
 * own off default - see blend_state_for_mode()).
 *
 * This slice does not implement any lighting model (MODEL_GEO_UNSHADED is
 * not distinguished - see warcraft_vert.vert/warcraft_frag.frag's header
 * comments for why), so that one MDX layer flag bit has no effect here;
 * every other flag/blend-mode combination proven above is implemented.
 */
#include "bz_quest_vk_wc3.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "bz_quest_log.h"
#include "bz_quest_pure.h"
#include "bz_quest_shaders_generated.h" /* generated by scripts/build-shaders.sh - see CMakeLists.txt */
#include "bz_quest_wc3_capture.h"

/* Shared, bounded staging buffer capacity - see bz_quest_vk_wc3.h's header
 * comment. 16MB covers this slice's largest single upload
 * (BZ_QUEST_WC3_MAX_TEXTURE_BYTES); a full model's combined vertex+index
 * arrays (<=~2.9MB at this slice's per-model caps) always fits inside it
 * too, so one shared buffer serves both upload kinds sequentially. */
enum { BZ_QUEST_VK_WC3_STAGING_BYTES = BZ_QUEST_WC3_MAX_TEXTURE_BYTES };

/* Raw MDX geoset/layer shading bit values this file reads from
 * bzQuestWc3LayerDesc_t::flags - mirrors games/warcraft-3/renderer/mdx/
 * r_mdx.h:27-35's mdxGeoFlags_t exactly (not #included directly: that
 * header pulls in renderer/r_local.h, the desktop engine's own internal
 * dependency surface, which this Quest-host module must stay free of -
 * see AGENTS.md's "Keep Android/OpenXR/Vulkan types out of shared bridge
 * headers" and this project's mirrored-constant precedent, e.g.
 * bz_quest_pure.c's BZ_QUEST_XR_COMPOSITION_LAYER_*_BIT_VALUE). */
enum {
    BZ_QUEST_MDX_GEO_TWOSIDED = 0x10,
    BZ_QUEST_MDX_GEO_NO_DEPTH_TEST = 0x40,
    BZ_QUEST_MDX_GEO_NO_DEPTH_SET = 0x80,
};

/* Mirrors platform/bridge/bz_tabletop_assets.h's bzTTBlendMode_t exactly.
 * Not #included directly for the same reason as the MDX_GEO_* bits above:
 * this module never touches the tabletop asset ABI (see this file's header
 * comment - only bz_quest_wc3_capture.c does), and bz_quest_wc3_render.h's
 * bzQuestWc3LayerDesc_t::blendMode already deliberately stores this as a
 * raw uint32_t rather than including that header either (same rationale,
 * see that field's comment). Cross-checked against the real enum by
 * bz_quest_wc3_capture.c's _Static_assert (the one file in this slice that
 * legitimately includes bz_tabletop_assets.h), so a future renumbering of
 * bzTTBlendMode_t fails the build here instead of silently mis-blending. */
enum {
    BZ_QUEST_TTA_BLEND_OPAQUE = 0,
    BZ_QUEST_TTA_BLEND_TRANSPARENT = 1,
    BZ_QUEST_TTA_BLEND_ALPHA = 2,
    BZ_QUEST_TTA_BLEND_ADDITIVE = 3,
    BZ_QUEST_TTA_BLEND_ADD_ALPHA = 4,
    BZ_QUEST_TTA_BLEND_MODULATE = 5,
    BZ_QUEST_TTA_BLEND_MODULATE_2X = 6,
};

static bool find_memory_type(VkPhysicalDevice physicalDevice, uint32_t typeBits,
                             VkMemoryPropertyFlags required, uint32_t *outIndex) {
    VkPhysicalDeviceMemoryProperties props;
    vkGetPhysicalDeviceMemoryProperties(physicalDevice, &props);
    for (uint32_t i = 0; i < props.memoryTypeCount; i++) {
        if (!(typeBits & (1u << i))) continue;
        if ((props.memoryTypes[i].propertyFlags & required) != required) continue;
        *outIndex = i;
        return true;
    }
    BZ_QUEST_LOGE("bz_quest_vk_wc3: no memory type matches bits=0x%x flags=0x%x", typeBits,
                  (unsigned)required);
    return false;
}

static bool create_shader_module(VkDevice device, const uint32_t *code, uint32_t codeLen,
                                 VkShaderModule *out) {
    VkShaderModuleCreateInfo info = {0};
    info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    info.codeSize = codeLen;
    info.pCode = code;
    if (vkCreateShaderModule(device, &info, NULL, out) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateShaderModule failed");
        return false;
    }
    return true;
}

/* Runs `record` (which must vkCmdCopyBuffer/vkCmdCopyBufferToImage/
 * vkCmdPipelineBarrier from `vk3->stagingBuffer`) on vk3->uploadCommandBuffer
 * as a one-time-submit command buffer, then blocks until the queue is idle
 * before returning - mirrors bz_quest_vk_render_target()'s own
 * fence-wait-before-return discipline (see bz_quest_vk_wc3.h's top comment)
 * so no upload is ever left in-flight when this function returns; the
 * caller may immediately reuse the staging buffer for the next upload. */
typedef void (*bzQuestVkWc3RecordFn)(VkCommandBuffer cmd, void *ctx);
static bool run_one_time_upload(bzQuestVkWc3_t *vk3, bzQuestVkWc3RecordFn record, void *ctx) {
    if (vkResetCommandBuffer(vk3->uploadCommandBuffer, 0) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkResetCommandBuffer (upload) failed");
        return false;
    }
    VkCommandBufferBeginInfo beginInfo = {0};
    beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    if (vkBeginCommandBuffer(vk3->uploadCommandBuffer, &beginInfo) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkBeginCommandBuffer (upload) failed");
        return false;
    }
    record(vk3->uploadCommandBuffer, ctx);
    if (vkEndCommandBuffer(vk3->uploadCommandBuffer) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkEndCommandBuffer (upload) failed");
        return false;
    }
    VkSubmitInfo submitInfo = {0};
    submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    submitInfo.commandBufferCount = 1;
    submitInfo.pCommandBuffers = &vk3->uploadCommandBuffer;
    /* No fence handoff needed here (unlike bz_quest_vk_render_target()'s
     * per-eye XR_KHR_vulkan_enable2 contract) - this queue is not shared
     * with an XR compositor's own synchronization requirement, so a plain
     * vkQueueWaitIdle() is sufficient and simpler than a dedicated fence. */
    if (vkQueueSubmit(vk3->vk->queue, 1, &submitInfo, VK_NULL_HANDLE) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkQueueSubmit (upload) failed");
        return false;
    }
    if (vkQueueWaitIdle(vk3->vk->queue) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkQueueWaitIdle (upload) failed");
        return false;
    }
    return true;
}

/* Read-only cache lookup that never triggers a create() call - unlike
 * bz_quest_wc3_cache_acquire(), which unconditionally creates on a miss.
 * bz_quest_vk_wc3_render_target() must never itself trigger a new upload
 * (all uploads happen only via bz_quest_vk_wc3_capture_and_upload(), which
 * is the sole, per-frame-budgeted caller of cache_acquire() - see this
 * file's header comment); this reads bzQuestWc3Cache_t's public slots[]
 * array directly, the same "sibling module reaches into public fields"
 * pattern bz_quest_vk.c's own callers already use for bzQuestVk_t. */
static void *cache_find(const bzQuestWc3Cache_t *cache, const char *identity) {
    for (uint32_t i = 0; i < cache->capacity; i++) {
        if (cache->slots[i].occupied && bz_quest_wc3_identity_equal(cache->slots[i].key.identity, identity))
            return cache->slots[i].handle;
    }
    return NULL;
}

/* ---------------------------------------------------------------------- */
/* Model GPU cache create/destroy                                         */
/* ---------------------------------------------------------------------- */

typedef struct {
    bzQuestVkWc3_t *vk3;
    uint32_t vertexBytes;
    uint32_t indexBytes;
    VkBuffer vertexBuffer, indexBuffer;
} ModelUploadCtx_t;

static void record_model_upload(VkCommandBuffer cmd, void *ctxPtr) {
    ModelUploadCtx_t *ctx = (ModelUploadCtx_t *)ctxPtr;
    VkBufferCopy vertexCopy = {0, 0, ctx->vertexBytes};
    vkCmdCopyBuffer(cmd, ctx->vk3->stagingBuffer, ctx->vertexBuffer, 1, &vertexCopy);
    VkBufferCopy indexCopy = {ctx->vertexBytes, 0, ctx->indexBytes};
    vkCmdCopyBuffer(cmd, ctx->vk3->stagingBuffer, ctx->indexBuffer, 1, &indexCopy);
}

static bool create_device_local_buffer(bzQuestVkWc3_t *vk3, VkDeviceSize size,
                                       VkBufferUsageFlags usage, VkBuffer *outBuffer,
                                       VkDeviceMemory *outMemory) {
    VkBufferCreateInfo bufferInfo = {0};
    bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bufferInfo.size = size;
    bufferInfo.usage = usage;
    bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(vk3->vk->device, &bufferInfo, NULL, outBuffer) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateBuffer failed");
        return false;
    }
    VkMemoryRequirements memReq;
    vkGetBufferMemoryRequirements(vk3->vk->device, *outBuffer, &memReq);
    uint32_t memoryTypeIndex = 0;
    if (!find_memory_type(vk3->vk->physicalDevice, memReq.memoryTypeBits,
                          VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, &memoryTypeIndex)) {
        vkDestroyBuffer(vk3->vk->device, *outBuffer, NULL);
        *outBuffer = VK_NULL_HANDLE;
        return false;
    }
    VkMemoryAllocateInfo allocInfo = {0};
    allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.allocationSize = memReq.size;
    allocInfo.memoryTypeIndex = memoryTypeIndex;
    if (vkAllocateMemory(vk3->vk->device, &allocInfo, NULL, outMemory) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkAllocateMemory failed");
        vkDestroyBuffer(vk3->vk->device, *outBuffer, NULL);
        *outBuffer = VK_NULL_HANDLE;
        return false;
    }
    if (vkBindBufferMemory(vk3->vk->device, *outBuffer, *outMemory, 0) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkBindBufferMemory failed");
        vkDestroyBuffer(vk3->vk->device, *outBuffer, NULL);
        vkFreeMemory(vk3->vk->device, *outMemory, NULL);
        *outBuffer = VK_NULL_HANDLE;
        *outMemory = VK_NULL_HANDLE;
        return false;
    }
    return true;
}

static void *model_cache_create(const bzQuestWc3CacheKey_t *key, void *userdata) {
    (void)key;
    bzQuestVkWc3_t *vk3 = (bzQuestVkWc3_t *)userdata;
    const bzQuestWc3Model_t *model = vk3->pendingModel;
    if (!model) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: model_cache_create called with no pending model");
        return NULL;
    }
    VkDeviceSize vertexBytes = (VkDeviceSize)model->meta.vertexCount * sizeof(bzQuestWc3Vertex_t);
    VkDeviceSize indexBytes = (VkDeviceSize)model->meta.indexCount * sizeof(uint32_t);
    if (vertexBytes == 0 || indexBytes == 0 ||
        vertexBytes + indexBytes > BZ_QUEST_VK_WC3_STAGING_BYTES) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: model '%s' has empty or oversized geometry (%llu+%llu bytes)",
                      model->meta.identity, (unsigned long long)vertexBytes,
                      (unsigned long long)indexBytes);
        return NULL;
    }

    VkBuffer vertexBuffer = VK_NULL_HANDLE, indexBuffer = VK_NULL_HANDLE;
    VkDeviceMemory vertexMemory = VK_NULL_HANDLE, indexMemory = VK_NULL_HANDLE;
    if (!create_device_local_buffer(vk3, vertexBytes,
                                    VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                                    &vertexBuffer, &vertexMemory))
        return NULL;
    if (!create_device_local_buffer(vk3, indexBytes,
                                    VK_BUFFER_USAGE_INDEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                                    &indexBuffer, &indexMemory)) {
        vkDestroyBuffer(vk3->vk->device, vertexBuffer, NULL);
        vkFreeMemory(vk3->vk->device, vertexMemory, NULL);
        return NULL;
    }

    void *mapped = NULL;
    if (vkMapMemory(vk3->vk->device, vk3->stagingMemory, 0, vertexBytes + indexBytes, 0, &mapped) !=
        VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkMapMemory (model staging) failed");
        goto fail;
    }
    memcpy(mapped, model->vertices, (size_t)vertexBytes);
    memcpy((uint8_t *)mapped + vertexBytes, model->indices, (size_t)indexBytes);
    vkUnmapMemory(vk3->vk->device, vk3->stagingMemory);

    {
        ModelUploadCtx_t ctx = {vk3, (uint32_t)vertexBytes, (uint32_t)indexBytes, vertexBuffer,
                                indexBuffer};
        if (!run_one_time_upload(vk3, record_model_upload, &ctx)) goto fail;
    }

    bzQuestVkWc3Model_t *out = (bzQuestVkWc3Model_t *)malloc(sizeof(bzQuestVkWc3Model_t));
    if (!out) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: malloc(bzQuestVkWc3Model_t) failed");
        goto fail;
    }
    out->vertexBuffer = vertexBuffer;
    out->indexBuffer = indexBuffer;
    out->vertexMemory = vertexMemory;
    out->indexMemory = indexMemory;
    out->meta = model->meta;
    return out;

fail:
    vkDestroyBuffer(vk3->vk->device, vertexBuffer, NULL);
    vkDestroyBuffer(vk3->vk->device, indexBuffer, NULL);
    vkFreeMemory(vk3->vk->device, vertexMemory, NULL);
    vkFreeMemory(vk3->vk->device, indexMemory, NULL);
    return NULL;
}

static void model_cache_destroy(void *handle, void *userdata) {
    bzQuestVkWc3_t *vk3 = (bzQuestVkWc3_t *)userdata;
    bzQuestVkWc3Model_t *m = (bzQuestVkWc3Model_t *)handle;
    if (m->vertexBuffer != VK_NULL_HANDLE) vkDestroyBuffer(vk3->vk->device, m->vertexBuffer, NULL);
    if (m->indexBuffer != VK_NULL_HANDLE) vkDestroyBuffer(vk3->vk->device, m->indexBuffer, NULL);
    if (m->vertexMemory != VK_NULL_HANDLE) vkFreeMemory(vk3->vk->device, m->vertexMemory, NULL);
    if (m->indexMemory != VK_NULL_HANDLE) vkFreeMemory(vk3->vk->device, m->indexMemory, NULL);
    /* Releases the bzQuestWc3ModelAnim_t arena transferred into this entry
     * by model_cache_create()'s `out->meta = model->meta` copy - see
     * model_ready_cb's ownership-transfer comment. NULL-safe. */
    bz_quest_wc3_model_anim_free((bzQuestWc3ModelAnim_t *)m->meta.anim);
    free(m);
}

/* ---------------------------------------------------------------------- */
/* Texture GPU cache create/destroy                                       */
/* ---------------------------------------------------------------------- */

typedef struct {
    VkImage image;
} TextureUploadCtx_t;

static void record_texture_upload(VkCommandBuffer cmd, void *ctxPtr) {
    TextureUploadCtx_t *ctx = (TextureUploadCtx_t *)ctxPtr;
    VkImageMemoryBarrier toDst = {0};
    toDst.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    toDst.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    toDst.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    toDst.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toDst.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toDst.image = ctx->image;
    toDst.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    toDst.subresourceRange.levelCount = 1;
    toDst.subresourceRange.layerCount = 1;
    toDst.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0,
                        0, NULL, 0, NULL, 1, &toDst);
}

static void *texture_cache_create(const bzQuestWc3CacheKey_t *key, void *userdata) {
    (void)key;
    bzQuestVkWc3_t *vk3 = (bzQuestVkWc3_t *)userdata;
    uint32_t width = vk3->pendingTextureWidth, height = vk3->pendingTextureHeight;
    uint32_t rowBytes = vk3->pendingTextureRowBytes;
    const uint8_t *pixels = vk3->pendingTexturePixels;
    if (!pixels || width == 0 || height == 0) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: texture_cache_create called with no pending texture");
        return NULL;
    }
    VkDeviceSize tightBytes = (VkDeviceSize)width * 4 * height;
    if (tightBytes > BZ_QUEST_VK_WC3_STAGING_BYTES) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: texture '%s' %ux%u exceeds staging capacity",
                      vk3->pendingTextureIdentity ? vk3->pendingTextureIdentity : "?", width, height);
        return NULL;
    }

    VkImageCreateInfo imageInfo = {0};
    imageInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    imageInfo.imageType = VK_IMAGE_TYPE_2D;
    imageInfo.format = VK_FORMAT_R8G8B8A8_UNORM;
    imageInfo.extent.width = width;
    imageInfo.extent.height = height;
    imageInfo.extent.depth = 1;
    imageInfo.mipLevels = 1;
    imageInfo.arrayLayers = 1;
    imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
    imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
    imageInfo.usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT;
    imageInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    imageInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    VkImage image = VK_NULL_HANDLE;
    if (vkCreateImage(vk3->vk->device, &imageInfo, NULL, &image) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateImage failed");
        return NULL;
    }
    VkMemoryRequirements memReq;
    vkGetImageMemoryRequirements(vk3->vk->device, image, &memReq);
    uint32_t memoryTypeIndex = 0;
    VkDeviceMemory memory = VK_NULL_HANDLE;
    if (!find_memory_type(vk3->vk->physicalDevice, memReq.memoryTypeBits,
                          VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, &memoryTypeIndex)) {
        vkDestroyImage(vk3->vk->device, image, NULL);
        return NULL;
    }
    VkMemoryAllocateInfo allocInfo = {0};
    allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.allocationSize = memReq.size;
    allocInfo.memoryTypeIndex = memoryTypeIndex;
    if (vkAllocateMemory(vk3->vk->device, &allocInfo, NULL, &memory) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkAllocateMemory (image) failed");
        vkDestroyImage(vk3->vk->device, image, NULL);
        return NULL;
    }
    if (vkBindImageMemory(vk3->vk->device, image, memory, 0) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkBindImageMemory failed");
        vkDestroyImage(vk3->vk->device, image, NULL);
        vkFreeMemory(vk3->vk->device, memory, NULL);
        return NULL;
    }

    void *mapped = NULL;
    if (vkMapMemory(vk3->vk->device, vk3->stagingMemory, 0, tightBytes, 0, &mapped) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkMapMemory (texture staging) failed");
        vkDestroyImage(vk3->vk->device, image, NULL);
        vkFreeMemory(vk3->vk->device, memory, NULL);
        return NULL;
    }
    /* Re-pack to a tight width*4 row stride: rowBytes may exceed width*4
     * (BLP row padding) but vkCmdCopyBufferToImage's bufferRowLength=0
     * default means "tightly packed", so the staging copy must already be
     * tightly packed regardless of the source's own row stride. */
    for (uint32_t y = 0; y < height; y++) {
        memcpy((uint8_t *)mapped + (size_t)y * width * 4, pixels + (size_t)y * rowBytes,
              (size_t)width * 4);
    }
    vkUnmapMemory(vk3->vk->device, vk3->stagingMemory);

    {
        TextureUploadCtx_t ctx = {image};
        /* record_texture_upload() only performs the UNDEFINED->TRANSFER_DST
         * barrier; the buffer->image copy and the final TRANSFER_DST->
         * SHADER_READ_ONLY barrier are recorded inline below (need
         * width/height, which run_one_time_upload()'s generic record
         * callback signature does not carry) - all three still happen
         * inside the SAME one-time-submit command buffer/queue-wait cycle
         * as record_texture_upload(), so this is one atomic upload, not
         * two. */
        if (vkResetCommandBuffer(vk3->uploadCommandBuffer, 0) != VK_SUCCESS) goto image_fail;
        VkCommandBufferBeginInfo beginInfo = {0};
        beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
        beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        if (vkBeginCommandBuffer(vk3->uploadCommandBuffer, &beginInfo) != VK_SUCCESS) goto image_fail;
        record_texture_upload(vk3->uploadCommandBuffer, &ctx);
        VkBufferImageCopy region = {0};
        region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        region.imageSubresource.layerCount = 1;
        region.imageExtent.width = width;
        region.imageExtent.height = height;
        region.imageExtent.depth = 1;
        vkCmdCopyBufferToImage(vk3->uploadCommandBuffer, vk3->stagingBuffer, image,
                              VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);
        VkImageMemoryBarrier toShaderRead = {0};
        toShaderRead.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
        toShaderRead.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
        toShaderRead.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
        toShaderRead.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        toShaderRead.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        toShaderRead.image = image;
        toShaderRead.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        toShaderRead.subresourceRange.levelCount = 1;
        toShaderRead.subresourceRange.layerCount = 1;
        toShaderRead.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        toShaderRead.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        vkCmdPipelineBarrier(vk3->uploadCommandBuffer, VK_PIPELINE_STAGE_TRANSFER_BIT,
                            VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 0, NULL, 0, NULL, 1,
                            &toShaderRead);
        if (vkEndCommandBuffer(vk3->uploadCommandBuffer) != VK_SUCCESS) goto image_fail;
        VkSubmitInfo submitInfo = {0};
        submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
        submitInfo.commandBufferCount = 1;
        submitInfo.pCommandBuffers = &vk3->uploadCommandBuffer;
        if (vkQueueSubmit(vk3->vk->queue, 1, &submitInfo, VK_NULL_HANDLE) != VK_SUCCESS)
            goto image_fail;
        if (vkQueueWaitIdle(vk3->vk->queue) != VK_SUCCESS) goto image_fail;
    }

    VkImageView view = VK_NULL_HANDLE;
    {
        VkImageViewCreateInfo viewInfo = {0};
        viewInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
        viewInfo.image = image;
        viewInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
        viewInfo.format = VK_FORMAT_R8G8B8A8_UNORM;
        viewInfo.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        viewInfo.subresourceRange.levelCount = 1;
        viewInfo.subresourceRange.layerCount = 1;
        if (vkCreateImageView(vk3->vk->device, &viewInfo, NULL, &view) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateImageView failed");
            goto image_fail;
        }
    }

    VkDescriptorSet descriptorSet = VK_NULL_HANDLE;
    {
        VkDescriptorSetAllocateInfo allocInfo2 = {0};
        allocInfo2.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
        allocInfo2.descriptorPool = vk3->descriptorPool;
        allocInfo2.descriptorSetCount = 1;
        allocInfo2.pSetLayouts = &vk3->descriptorSetLayout;
        if (vkAllocateDescriptorSets(vk3->vk->device, &allocInfo2, &descriptorSet) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkAllocateDescriptorSets failed");
            vkDestroyImageView(vk3->vk->device, view, NULL);
            goto image_fail;
        }
        VkDescriptorImageInfo imageDescInfo = {0};
        imageDescInfo.sampler = vk3->sampler;
        imageDescInfo.imageView = view;
        imageDescInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
        VkWriteDescriptorSet write = {0};
        write.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        write.dstSet = descriptorSet;
        write.dstBinding = 0;
        write.descriptorCount = 1;
        write.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        write.pImageInfo = &imageDescInfo;
        vkUpdateDescriptorSets(vk3->vk->device, 1, &write, 0, NULL);
    }

    bzQuestVkWc3Texture_t *out = (bzQuestVkWc3Texture_t *)malloc(sizeof(bzQuestVkWc3Texture_t));
    if (!out) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: malloc(bzQuestVkWc3Texture_t) failed");
        vkFreeDescriptorSets(vk3->vk->device, vk3->descriptorPool, 1, &descriptorSet);
        vkDestroyImageView(vk3->vk->device, view, NULL);
        goto image_fail;
    }
    out->image = image;
    out->memory = memory;
    out->view = view;
    out->descriptorSet = descriptorSet;
    return out;

image_fail:
    vkDestroyImage(vk3->vk->device, image, NULL);
    vkFreeMemory(vk3->vk->device, memory, NULL);
    return NULL;
}

static void texture_cache_destroy(void *handle, void *userdata) {
    bzQuestVkWc3_t *vk3 = (bzQuestVkWc3_t *)userdata;
    bzQuestVkWc3Texture_t *t = (bzQuestVkWc3Texture_t *)handle;
    if (t->descriptorSet != VK_NULL_HANDLE)
        vkFreeDescriptorSets(vk3->vk->device, vk3->descriptorPool, 1, &t->descriptorSet);
    if (t->view != VK_NULL_HANDLE) vkDestroyImageView(vk3->vk->device, t->view, NULL);
    if (t->image != VK_NULL_HANDLE) vkDestroyImage(vk3->vk->device, t->image, NULL);
    if (t->memory != VK_NULL_HANDLE) vkFreeMemory(vk3->vk->device, t->memory, NULL);
    free(t);
}

/* ---------------------------------------------------------------------- */
/* Capture callbacks - the only call sites that may trigger a cache miss  */
/* upload (see bz_quest_vk_wc3.h's capture_and_upload contract).          */
/* ---------------------------------------------------------------------- */

static void model_ready_cb(const bzQuestWc3Model_t *model, void *userdata) {
    bzQuestVkWc3_t *vk3 = (bzQuestVkWc3_t *)userdata;
    if (cache_find(&vk3->modelCache, model->meta.identity)) {
        /* Already resident. bz_quest_wc3_capture.c's per-frame dedup only
         * spans one frame (see its s_seenModelConfigIndex comment), so
         * decode_model() unconditionally rebuilds a fresh
         * bzQuestWc3ModelAnim_t arena every time an already-cached model is
         * re-offered - this offering's copy is surplus (the resident cache
         * entry already owns its own arena from its original upload - see
         * model_cache_create's `out->meta = model->meta` ownership
         * transfer) and must be released here, or it leaks. */
        bz_quest_wc3_model_anim_free((bzQuestWc3ModelAnim_t *)model->meta.anim);
        return;
    }
    if (vk3->newModelUploadsThisFrame >= BZ_QUEST_VK_WC3_MAX_NEW_MODEL_UPLOADS_PER_FRAME) {
        /* Bounded per this file's header comment - picked up next frame,
         * since bz_quest_wc3_capture.c's per-frame dedup resets every
         * call, so a still-uncached model is offered again next frame.
         * This offering's arena is never handed to model_cache_create, so
         * it must be released here (see the "already resident" comment
         * above). */
        bz_quest_wc3_model_anim_free((bzQuestWc3ModelAnim_t *)model->meta.anim);
        return;
    }
    bzQuestWc3CacheKey_t key;
    memset(&key, 0, sizeof(key));
    strncpy(key.identity, model->meta.identity, sizeof(key.identity) - 1);
    key.variant = BZ_QUEST_WC3_VARIANT_NONE;
    vk3->pendingModel = model;
    void *handle = NULL;
    if (bz_quest_wc3_cache_acquire(&vk3->modelCache, &key, &handle)) {
        vk3->newModelUploadsThisFrame++;
        /* Success: model_cache_create() copied `model->meta` (including the
         * meta.anim pointer) into the new persistent cache entry by value -
         * ownership of the arena is now that cache entry's, released by
         * model_cache_destroy() on eviction/shutdown. Do not free here. */
    } else {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: model '%s' GPU upload failed", model->meta.identity);
        /* model_cache_create() failed before ever allocating a cache entry
         * to transfer ownership into - this offering's arena is otherwise
         * unowned and must be released here. */
        bz_quest_wc3_model_anim_free((bzQuestWc3ModelAnim_t *)model->meta.anim);
    }
    vk3->pendingModel = NULL;
}

static void texture_ready_cb(const char *identity, uint32_t width, uint32_t height,
                            uint32_t rowBytes, const uint8_t *pixels, uint32_t dataBytes,
                            void *userdata) {
    (void)dataBytes;
    bzQuestVkWc3_t *vk3 = (bzQuestVkWc3_t *)userdata;
    if (cache_find(&vk3->textureCache, identity)) return; /* already resident */
    if (vk3->newTextureUploadsThisFrame >= BZ_QUEST_VK_WC3_MAX_NEW_TEXTURE_UPLOADS_PER_FRAME) {
        return; /* picked up next frame - see model_ready_cb's identical rationale */
    }
    bzQuestWc3CacheKey_t key;
    memset(&key, 0, sizeof(key));
    strncpy(key.identity, identity, sizeof(key.identity) - 1);
    key.variant = BZ_QUEST_WC3_VARIANT_NONE;
    vk3->pendingTextureIdentity = identity;
    vk3->pendingTextureWidth = width;
    vk3->pendingTextureHeight = height;
    vk3->pendingTextureRowBytes = rowBytes;
    vk3->pendingTexturePixels = pixels;
    void *handle = NULL;
    if (bz_quest_wc3_cache_acquire(&vk3->textureCache, &key, &handle)) {
        vk3->newTextureUploadsThisFrame++;
    } else {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: texture '%s' GPU upload failed", identity);
    }
    vk3->pendingTextureIdentity = NULL;
    vk3->pendingTexturePixels = NULL;
}

/*
 * Forward-declared here (defined later in this file, alongside draw_layer()/
 * record_opaque()/record_blended() - its actual consumers - since it
 * depends on types/helpers declared in between): computes this frame's
 * authoritative per-(render item, geoset) bone palette and geoset alpha.
 * Called once per frame from bz_quest_vk_wc3_capture_and_upload() below,
 * never from record_opaque()/record_blended() (which run once per eye) -
 * see this function's full doc comment at its definition.
 */
static void build_frame_dynamic_material(bzQuestVkWc3_t *vk3, const bzQuestWc3RenderList_t *list);

void bz_quest_vk_wc3_capture_and_upload(bzQuestVkWc3_t *vk3, bzQuestWc3RenderList_t *outRenderList) {
    vk3->newModelUploadsThisFrame = 0;
    vk3->newTextureUploadsThisFrame = 0;
    bzQuestWc3CaptureCallbacks_t callbacks;
    callbacks.onModelReady = model_ready_cb;
    callbacks.modelUserdata = vk3;
    callbacks.onTextureReady = texture_ready_cb;
    callbacks.textureUserdata = vk3;
    bz_quest_wc3_capture_frame(&callbacks, outRenderList);
    /* Runs exactly once per frame here (not once per eye - see
     * bz_quest_vk_wc3.h's paletteSlotsUsedThisFrame doc comment), after the
     * model-cache upload pass above so every resident model's animation
     * data is reachable via cache_find() for record_opaque()/
     * record_blended() (called once per eye, later) to consume via
     * s_paletteByteOffset/s_geosetAlpha - see build_frame_dynamic_
     * material()'s own doc comment, defined further below in this file
     * (forward-declared just above). */
    build_frame_dynamic_material(vk3, outRenderList);
}

/* ---------------------------------------------------------------------- */
/* Pipeline variants                                                       */
/* ---------------------------------------------------------------------- */

/* blend_state_for_mode()'s single source of truth - see this file's header
 * comment for the exact desktop-engine evidence each row reproduces. */
static void blend_state_for_mode(uint32_t blendMode, VkPipelineColorBlendAttachmentState *outBlend,
                                 bool *outDepthWriteDefault) {
    memset(outBlend, 0, sizeof(*outBlend));
    outBlend->colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                              VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    outBlend->colorBlendOp = VK_BLEND_OP_ADD;
    outBlend->alphaBlendOp = VK_BLEND_OP_ADD;
    switch (blendMode) {
        case BZ_QUEST_TTA_BLEND_ALPHA:
            outBlend->blendEnable = VK_TRUE;
            outBlend->srcColorBlendFactor = outBlend->srcAlphaBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
            outBlend->dstColorBlendFactor = outBlend->dstAlphaBlendFactor =
                VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
            *outDepthWriteDefault = false;
            break;
        case BZ_QUEST_TTA_BLEND_ADDITIVE:
            outBlend->blendEnable = VK_TRUE;
            outBlend->srcColorBlendFactor = outBlend->srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
            outBlend->dstColorBlendFactor = outBlend->dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
            *outDepthWriteDefault = false;
            break;
        case BZ_QUEST_TTA_BLEND_ADD_ALPHA:
            outBlend->blendEnable = VK_TRUE;
            outBlend->srcColorBlendFactor = outBlend->srcAlphaBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
            outBlend->dstColorBlendFactor = outBlend->dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
            *outDepthWriteDefault = false;
            break;
        case BZ_QUEST_TTA_BLEND_MODULATE:
            outBlend->blendEnable = VK_TRUE;
            outBlend->srcColorBlendFactor = outBlend->srcAlphaBlendFactor = VK_BLEND_FACTOR_DST_COLOR;
            outBlend->dstColorBlendFactor = outBlend->dstAlphaBlendFactor = VK_BLEND_FACTOR_ZERO;
            *outDepthWriteDefault = false;
            break;
        case BZ_QUEST_TTA_BLEND_MODULATE_2X:
            outBlend->blendEnable = VK_TRUE;
            outBlend->srcColorBlendFactor = outBlend->srcAlphaBlendFactor = VK_BLEND_FACTOR_DST_COLOR;
            outBlend->dstColorBlendFactor = outBlend->dstAlphaBlendFactor = VK_BLEND_FACTOR_SRC_COLOR;
            *outDepthWriteDefault = false;
            break;
        case BZ_QUEST_TTA_BLEND_OPAQUE:
        case BZ_QUEST_TTA_BLEND_TRANSPARENT:
        default:
            outBlend->blendEnable = VK_FALSE;
            *outDepthWriteDefault = true;
            break;
    }
}

static VkPipeline create_pipeline_variant(bzQuestVkWc3_t *vk3, uint32_t blendMode, bool twoSided,
                                          bool depthTestEnable, bool depthWriteEnable) {
    VkPipelineShaderStageCreateInfo stages[2];
    memset(stages, 0, sizeof(stages));
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vk3->vertexShader;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = vk3->fragmentShader;
    stages[1].pName = "main";

    VkVertexInputBindingDescription binding = {0, sizeof(bzQuestWc3Vertex_t), VK_VERTEX_INPUT_RATE_VERTEX};
    /* Bone index (location 2) is VK_FORMAT_R8G8B8A8_UINT (read as GLSL
     * uvec4, unnormalized) and bone weight (location 3) is
     * VK_FORMAT_R8G8B8A8_UNORM (read as GLSL vec4, hardware-normalized
     * 0..255 -> 0.0..1.0) - this exactly reproduces the desktop engine's
     * own vertex-attribute format for the same two fields:
     * renderer/r_buffer.c:87-88's `glVertexAttribPointer(attrib_skin1, 4,
     * GL_UNSIGNED_BYTE, GL_FALSE, ...)` (unnormalized) and
     * `glVertexAttribPointer(attrib_boneWeight1, 4, GL_UNSIGNED_BYTE,
     * GL_TRUE, ...)` (normalized) respectively - see warcraft_vert.vert's
     * header comment for the matching skinning formula
     * (renderer/r_shader.c:227-229). */
    VkVertexInputAttributeDescription attrs[4] = {
        {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(bzQuestWc3Vertex_t, position)},
        {1, 0, VK_FORMAT_R32G32_SFLOAT, offsetof(bzQuestWc3Vertex_t, uv)},
        {2, 0, VK_FORMAT_R8G8B8A8_UINT, offsetof(bzQuestWc3Vertex_t, boneIndex)},
        {3, 0, VK_FORMAT_R8G8B8A8_UNORM, offsetof(bzQuestWc3Vertex_t, boneWeight)},
    };
    VkPipelineVertexInputStateCreateInfo vertexInput = {0};
    vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vertexInput.vertexBindingDescriptionCount = 1;
    vertexInput.pVertexBindingDescriptions = &binding;
    vertexInput.vertexAttributeDescriptionCount = 4;
    vertexInput.pVertexAttributeDescriptions = attrs;

    VkPipelineInputAssemblyStateCreateInfo inputAssembly = {0};
    inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo viewportState = {0};
    viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewportState.viewportCount = 1;
    viewportState.scissorCount = 1;

    VkPipelineRasterizationStateCreateInfo rasterization = {0};
    rasterization.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rasterization.polygonMode = VK_POLYGON_MODE_FILL;
    /* MODEL_GEO_TWOSIDED -> no culling; else back-face culling with the
     * same CCW front-face convention bz_quest_vk.c's own pipeline uses,
     * consistent with this slice's winding fix (see
     * bz_quest_wc3_render.h's coordinate evidence) - see this file's
     * header comment. */
    rasterization.cullMode = twoSided ? VK_CULL_MODE_NONE : VK_CULL_MODE_BACK_BIT;
    rasterization.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rasterization.lineWidth = 1.0f;

    VkPipelineMultisampleStateCreateInfo multisample = {0};
    multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineDepthStencilStateCreateInfo depthStencil = {0};
    depthStencil.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    depthStencil.depthTestEnable = depthTestEnable ? VK_TRUE : VK_FALSE;
    depthStencil.depthWriteEnable = depthWriteEnable ? VK_TRUE : VK_FALSE;
    depthStencil.depthCompareOp = VK_COMPARE_OP_LESS;

    VkPipelineColorBlendAttachmentState blendAttachment;
    bool depthWriteDefaultUnused = false;
    blend_state_for_mode(blendMode, &blendAttachment, &depthWriteDefaultUnused);

    VkPipelineColorBlendStateCreateInfo colorBlend = {0};
    colorBlend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    colorBlend.attachmentCount = 1;
    colorBlend.pAttachments = &blendAttachment;

    static const VkDynamicState kDynamicStates[2] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dynamicState = {0};
    dynamicState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamicState.dynamicStateCount = 2;
    dynamicState.pDynamicStates = kDynamicStates;

    VkGraphicsPipelineCreateInfo pipelineCreateInfo = {0};
    pipelineCreateInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pipelineCreateInfo.stageCount = 2;
    pipelineCreateInfo.pStages = stages;
    pipelineCreateInfo.pVertexInputState = &vertexInput;
    pipelineCreateInfo.pInputAssemblyState = &inputAssembly;
    pipelineCreateInfo.pViewportState = &viewportState;
    pipelineCreateInfo.pRasterizationState = &rasterization;
    pipelineCreateInfo.pMultisampleState = &multisample;
    pipelineCreateInfo.pDepthStencilState = &depthStencil;
    pipelineCreateInfo.pColorBlendState = &colorBlend;
    pipelineCreateInfo.pDynamicState = &dynamicState;
    pipelineCreateInfo.layout = vk3->pipelineLayout;
    pipelineCreateInfo.renderPass = vk3->vk->renderPass;
    pipelineCreateInfo.subpass = 0;

    VkPipeline pipeline = VK_NULL_HANDLE;
    if (vkCreateGraphicsPipelines(vk3->vk->device, VK_NULL_HANDLE, 1, &pipelineCreateInfo, NULL,
                                  &pipeline) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateGraphicsPipelines (variant) failed");
        return VK_NULL_HANDLE;
    }
    return pipeline;
}

static VkPipeline get_or_create_pipeline_variant(bzQuestVkWc3_t *vk3, uint32_t blendMode,
                                                 bool twoSided, bool depthTestEnable,
                                                 bool depthWriteEnable) {
    for (uint32_t i = 0; i < vk3->pipelineVariantCount; i++) {
        bzQuestVkWc3PipelineVariant_t *v = &vk3->pipelineVariants[i];
        if (v->blendMode == blendMode && v->twoSided == twoSided &&
            v->depthTestEnable == depthTestEnable && v->depthWriteEnable == depthWriteEnable)
            return v->pipeline;
    }
    if (vk3->pipelineVariantCount >= BZ_QUEST_VK_WC3_MAX_PIPELINE_VARIANTS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: pipeline variant cache exhausted (%u) - reusing variant 0",
                      (uint32_t)BZ_QUEST_VK_WC3_MAX_PIPELINE_VARIANTS);
        return vk3->pipelineVariantCount > 0 ? vk3->pipelineVariants[0].pipeline : VK_NULL_HANDLE;
    }
    VkPipeline pipeline = create_pipeline_variant(vk3, blendMode, twoSided, depthTestEnable,
                                                  depthWriteEnable);
    if (pipeline == VK_NULL_HANDLE) return VK_NULL_HANDLE;
    bzQuestVkWc3PipelineVariant_t *v = &vk3->pipelineVariants[vk3->pipelineVariantCount++];
    v->blendMode = blendMode;
    v->twoSided = twoSided;
    v->depthTestEnable = depthTestEnable;
    v->depthWriteEnable = depthWriteEnable;
    v->pipeline = pipeline;
    return pipeline;
}

/* ---------------------------------------------------------------------- */
/* Bone-palette dynamic-offset UBO (layer 5C GPU skinning)                 */
/* ---------------------------------------------------------------------- */

/* Creates out->paletteDescriptorSetLayout/Pool/Set, out->paletteBuffer/
 * Memory (persistently mapped), and out->paletteSlotStride - see
 * bzQuestVkWc3_t's paletteBuffer doc comment. Must run before pipeline
 * layout creation (which references paletteDescriptorSetLayout). Slot 0 is
 * written here, once, as BZ_QUEST_WC3_MAX_MATRIX_PALETTE identity matrices
 * - the permanent fallback for static geometry / budget overflow (see
 * BZ_QUEST_VK_WC3_PALETTE_SLOT_COUNT's doc comment). Fails loudly (never
 * silently clamps) if the device's own minUniformBufferOffsetAlignment
 * makes one slot exceed maxUniformBufferRange - that would mean this
 * slice's fixed 128-mat4 palette size is not supported by this device at
 * all, which no per-frame code path could work around. */
static bool create_palette_resources(bzQuestVkWc3_t *out) {
    VkPhysicalDeviceProperties props;
    vkGetPhysicalDeviceProperties(out->vk->physicalDevice, &props);
    VkDeviceSize unaligned = (VkDeviceSize)BZ_QUEST_WC3_MAX_MATRIX_PALETTE * sizeof(float) * 16;
    VkDeviceSize align = props.limits.minUniformBufferOffsetAlignment;
    /* Round unaligned up to the next multiple of align (align is always a
     * power of two per the Vulkan spec) - the same "round up to alignment"
     * idiom used throughout this codebase's own buffer-packing code. */
    VkDeviceSize slotStride = align > 0 ? ((unaligned + align - 1) / align) * align : unaligned;
    if (slotStride > props.limits.maxUniformBufferRange) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: one bone-palette slot (%llu bytes, aligned from %llu) "
                      "exceeds this device's maxUniformBufferRange (%u) - cannot skin models",
                      (unsigned long long)slotStride, (unsigned long long)unaligned,
                      (uint32_t)props.limits.maxUniformBufferRange);
        return false;
    }
    out->paletteSlotStride = slotStride;

    VkDescriptorSetLayoutBinding binding = {0};
    binding.binding = 0;
    binding.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC;
    binding.descriptorCount = 1;
    binding.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
    VkDescriptorSetLayoutCreateInfo layoutInfo = {0};
    layoutInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    layoutInfo.bindingCount = 1;
    layoutInfo.pBindings = &binding;
    if (vkCreateDescriptorSetLayout(out->vk->device, &layoutInfo, NULL,
                                    &out->paletteDescriptorSetLayout) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateDescriptorSetLayout (palette) failed");
        return false;
    }

    {
        /* Exactly one set, ever - unlike the per-texture pool, this set is
         * reused across every draw via a different dynamic offset per
         * vkCmdBindDescriptorSets call, so no per-model/per-texture
         * allocation churn or descriptor-pool-headroom concern applies
         * here (contrast BZ_QUEST_VK_WC3_TEXTURE_DESCRIPTOR_POOL_CAPACITY's
         * doc comment in bz_quest_vk_wc3.h). */
        VkDescriptorPoolSize poolSize = {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, 1};
        VkDescriptorPoolCreateInfo poolInfo = {0};
        poolInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
        poolInfo.maxSets = 1;
        poolInfo.poolSizeCount = 1;
        poolInfo.pPoolSizes = &poolSize;
        if (vkCreateDescriptorPool(out->vk->device, &poolInfo, NULL, &out->paletteDescriptorPool) !=
            VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateDescriptorPool (palette) failed");
            return false;
        }
    }

    {
        VkBufferCreateInfo bufferInfo = {0};
        bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        bufferInfo.size = out->paletteSlotStride * BZ_QUEST_VK_WC3_PALETTE_SLOT_COUNT;
        bufferInfo.usage = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT;
        bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        if (vkCreateBuffer(out->vk->device, &bufferInfo, NULL, &out->paletteBuffer) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateBuffer (palette) failed");
            return false;
        }
        VkMemoryRequirements memReq;
        vkGetBufferMemoryRequirements(out->vk->device, out->paletteBuffer, &memReq);
        uint32_t memoryTypeIndex = 0;
        if (!find_memory_type(out->vk->physicalDevice, memReq.memoryTypeBits,
                              VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                              &memoryTypeIndex))
            return false;
        VkMemoryAllocateInfo allocInfo = {0};
        allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        allocInfo.allocationSize = memReq.size;
        allocInfo.memoryTypeIndex = memoryTypeIndex;
        if (vkAllocateMemory(out->vk->device, &allocInfo, NULL, &out->paletteMemory) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkAllocateMemory (palette) failed");
            return false;
        }
        if (vkBindBufferMemory(out->vk->device, out->paletteBuffer, out->paletteMemory, 0) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkBindBufferMemory (palette) failed");
            return false;
        }
        if (vkMapMemory(out->vk->device, out->paletteMemory, 0, bufferInfo.size, 0,
                        &out->paletteMapped) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkMapMemory (palette) failed");
            return false;
        }
    }

    {
        VkDescriptorSetAllocateInfo allocInfo = {0};
        allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
        allocInfo.descriptorPool = out->paletteDescriptorPool;
        allocInfo.descriptorSetCount = 1;
        allocInfo.pSetLayouts = &out->paletteDescriptorSetLayout;
        if (vkAllocateDescriptorSets(out->vk->device, &allocInfo, &out->paletteDescriptorSet) !=
            VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkAllocateDescriptorSets (palette) failed");
            return false;
        }
        VkDescriptorBufferInfo bufInfo = {out->paletteBuffer, 0, out->paletteSlotStride};
        VkWriteDescriptorSet write = {0};
        write.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        write.dstSet = out->paletteDescriptorSet;
        write.dstBinding = 0;
        write.descriptorCount = 1;
        write.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC;
        write.pBufferInfo = &bufInfo;
        vkUpdateDescriptorSets(out->vk->device, 1, &write, 0, NULL);
    }

    /* Slot 0: BZ_QUEST_WC3_MAX_MATRIX_PALETTE identity mat4s, written once
     * and never touched again - see BZ_QUEST_VK_WC3_PALETTE_SLOT_COUNT's
     * doc comment. bz_quest_mat4_multiply's column-major layout means an
     * identity mat4 is just 1.0 at v[0],v[5],v[10],v[15] and 0.0 elsewhere. */
    {
        float *identitySlot = (float *)out->paletteMapped;
        memset(identitySlot, 0, (size_t)out->paletteSlotStride);
        for (uint32_t b = 0; b < BZ_QUEST_WC3_MAX_MATRIX_PALETTE; b++) {
            float *m = identitySlot + (size_t)b * 16;
            m[0] = m[5] = m[10] = m[15] = 1.0f;
        }
    }

    return true;
}

/* ---------------------------------------------------------------------- */
/* Create / destroy                                                        */
/* ---------------------------------------------------------------------- */

bool bz_quest_vk_wc3_create(const bzQuestVk_t *vk, bzQuestVkWc3_t *out) {
    memset(out, 0, sizeof(*out));
    out->vk = vk;

    VkDescriptorSetLayoutBinding binding = {0};
    binding.binding = 0;
    binding.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
    binding.descriptorCount = 1;
    binding.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
    VkDescriptorSetLayoutCreateInfo layoutInfo = {0};
    layoutInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    layoutInfo.bindingCount = 1;
    layoutInfo.pBindings = &binding;
    if (vkCreateDescriptorSetLayout(vk->device, &layoutInfo, NULL, &out->descriptorSetLayout) !=
        VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateDescriptorSetLayout failed");
        goto fail;
    }

    {
        /* Sized to BZ_QUEST_VK_WC3_TEXTURE_DESCRIPTOR_POOL_CAPACITY (capacity
         * + 1 spare set), NOT the bare BZ_QUEST_VK_WC3_TEXTURE_CACHE_CAPACITY
         * - see that constant's doc comment in bz_quest_vk_wc3.h for why a
         * pool sized to exactly `capacity` sets deadlocks the texture cache
         * the first time a (capacity+1)-th distinct texture is requested. */
        VkDescriptorPoolSize poolSize = {VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
                                        BZ_QUEST_VK_WC3_TEXTURE_DESCRIPTOR_POOL_CAPACITY};
        VkDescriptorPoolCreateInfo poolInfo = {0};
        poolInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
        poolInfo.flags = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
        poolInfo.maxSets = BZ_QUEST_VK_WC3_TEXTURE_DESCRIPTOR_POOL_CAPACITY;
        poolInfo.poolSizeCount = 1;
        poolInfo.pPoolSizes = &poolSize;
        if (vkCreateDescriptorPool(vk->device, &poolInfo, NULL, &out->descriptorPool) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateDescriptorPool failed");
            goto fail;
        }
    }

    {
        /* Single shared REPEAT-addressed linear sampler - see
         * bz_quest_wc3_render.h's texture wrap-mode evidence for why no
         * per-texture wrap configuration is needed this slice. */
        VkSamplerCreateInfo samplerInfo = {0};
        samplerInfo.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
        samplerInfo.magFilter = VK_FILTER_LINEAR;
        samplerInfo.minFilter = VK_FILTER_LINEAR;
        samplerInfo.addressModeU = VK_SAMPLER_ADDRESS_MODE_REPEAT;
        samplerInfo.addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT;
        samplerInfo.addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT;
        samplerInfo.maxLod = 0.25f;
        if (vkCreateSampler(vk->device, &samplerInfo, NULL, &out->sampler) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateSampler failed");
            goto fail;
        }
    }

    if (!create_palette_resources(out)) goto fail;

    if (!create_shader_module(vk->device, g_bz_quest_warcraft_vert_spv, g_bz_quest_warcraft_vert_spv_len,
                              &out->vertexShader))
        goto fail;
    if (!create_shader_module(vk->device, g_bz_quest_warcraft_frag_spv, g_bz_quest_warcraft_frag_spv_len,
                              &out->fragmentShader))
        goto fail;

    {
        /* Two non-overlapping ranges - see bz_quest_vk_wc3.h's push-constant
         * layout doc comment: 64 bytes of vertex-stage mvp at offset 0, 16
         * bytes of fragment-stage material params at offset 64. 80 bytes
         * total, safely under Vulkan's guaranteed-minimum 128-byte
         * maxPushConstantsSize. */
        VkPushConstantRange ranges[2];
        ranges[0].stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
        ranges[0].offset = 0;
        ranges[0].size = sizeof(float) * 16;
        ranges[1].stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
        ranges[1].offset = sizeof(float) * 16;
        ranges[1].size = sizeof(float) * 4;
        /* Set 0 = per-texture combined-image-sampler (existing 5A layout),
         * set 1 = the shared bone-palette dynamic-offset UBO (see
         * bzQuestVkWc3_t's paletteDescriptorSetLayout doc comment) - both
         * bound together by draw_layer()'s single vkCmdBindDescriptorSets
         * call. */
        VkDescriptorSetLayout setLayouts[2] = {out->descriptorSetLayout, out->paletteDescriptorSetLayout};
        VkPipelineLayoutCreateInfo layoutCreateInfo = {0};
        layoutCreateInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
        layoutCreateInfo.setLayoutCount = 2;
        layoutCreateInfo.pSetLayouts = setLayouts;
        layoutCreateInfo.pushConstantRangeCount = 2;
        layoutCreateInfo.pPushConstantRanges = ranges;
        if (vkCreatePipelineLayout(vk->device, &layoutCreateInfo, NULL, &out->pipelineLayout) !=
            VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreatePipelineLayout failed");
            goto fail;
        }
    }

    {
        VkBufferCreateInfo bufferInfo = {0};
        bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        bufferInfo.size = BZ_QUEST_VK_WC3_STAGING_BYTES;
        bufferInfo.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
        bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        if (vkCreateBuffer(vk->device, &bufferInfo, NULL, &out->stagingBuffer) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkCreateBuffer (staging) failed");
            goto fail;
        }
        VkMemoryRequirements memReq;
        vkGetBufferMemoryRequirements(vk->device, out->stagingBuffer, &memReq);
        uint32_t memoryTypeIndex = 0;
        if (!find_memory_type(vk->physicalDevice, memReq.memoryTypeBits,
                              VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                              &memoryTypeIndex))
            goto fail;
        VkMemoryAllocateInfo allocInfo = {0};
        allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        allocInfo.allocationSize = memReq.size;
        allocInfo.memoryTypeIndex = memoryTypeIndex;
        if (vkAllocateMemory(vk->device, &allocInfo, NULL, &out->stagingMemory) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkAllocateMemory (staging) failed");
            goto fail;
        }
        if (vkBindBufferMemory(vk->device, out->stagingBuffer, out->stagingMemory, 0) != VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkBindBufferMemory (staging) failed");
            goto fail;
        }
    }

    {
        VkCommandBufferAllocateInfo cmdAllocInfo = {0};
        cmdAllocInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
        cmdAllocInfo.commandPool = vk->commandPool;
        cmdAllocInfo.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        cmdAllocInfo.commandBufferCount = 1;
        if (vkAllocateCommandBuffers(vk->device, &cmdAllocInfo, &out->uploadCommandBuffer) !=
            VK_SUCCESS) {
            BZ_QUEST_LOGE("bz_quest_vk_wc3: vkAllocateCommandBuffers (upload) failed");
            goto fail;
        }
    }

    if (!bz_quest_wc3_cache_init(&out->modelCache, BZ_QUEST_VK_WC3_MODEL_CACHE_CAPACITY,
                                model_cache_create, model_cache_destroy, out))
        goto fail;
    if (!bz_quest_wc3_cache_init(&out->textureCache, BZ_QUEST_VK_WC3_TEXTURE_CACHE_CAPACITY,
                                texture_cache_create, texture_cache_destroy, out))
        goto fail;

    BZ_QUEST_LOGI("bz_quest_vk_wc3: init complete");
    return true;

fail:
    BZ_QUEST_LOGE("bz_quest_vk_wc3: init failed - tearing down partial state");
    bz_quest_vk_wc3_destroy(out);
    return false;
}

/* ---------------------------------------------------------------------- */
/* Render                                                                  */
/* ---------------------------------------------------------------------- */

typedef struct {
    uint32_t itemIndex, geosetIndex, layerIndex;
    float distanceSq;
} BlendedDraw_t;

static BlendedDraw_t s_blendedDraws[BZ_QUEST_WC3_MAX_RENDER_ITEMS * BZ_QUEST_WC3_MAX_GEOSETS_PER_MODEL];
static uint32_t s_blendedDrawCount;

static float distance_sq(const float world[16], const float cameraWorldPos[3]) {
    float dx = world[12] - cameraWorldPos[0];
    float dy = world[13] - cameraWorldPos[1];
    float dz = world[14] - cameraWorldPos[2];
    return dx * dx + dy * dy + dz * dz;
}

static int compare_blended_draw_farthest_first(const void *a, const void *b) {
    const BlendedDraw_t *ba = (const BlendedDraw_t *)a;
    const BlendedDraw_t *bb = (const BlendedDraw_t *)b;
    if (ba->distanceSq > bb->distanceSq) return -1;
    if (ba->distanceSq < bb->distanceSq) return 1;
    return 0;
}

/* ---------------------------------------------------------------------- */
/* Per-frame bone-palette / geoset-alpha build (layer 5C dynamic material) */
/* ---------------------------------------------------------------------- */

/* This file's own copy of capture.c's log-once idiom (see that file's
 * LOG_ONCE macro) - deliberately file-local rather than shared, matching
 * this project's existing convention of one dedup table per translation
 * unit (each file's own diagnostics are about that file's own decisions). */
enum { BZ_QUEST_VK_WC3_MAX_LOGGED_KEYS = 256 };
static char s_vkWc3LoggedKeys[BZ_QUEST_VK_WC3_MAX_LOGGED_KEYS][BZ_QUEST_WC3_MAX_IDENTITY + 32];
static uint32_t s_vkWc3LoggedKeyCount;

static bool vk_wc3_log_once(const char *identity, const char *detail) {
    char key[BZ_QUEST_WC3_MAX_IDENTITY + 32];
    snprintf(key, sizeof(key), "%s|%s", identity, detail);
    for (uint32_t i = 0; i < s_vkWc3LoggedKeyCount; i++)
        if (strcmp(s_vkWc3LoggedKeys[i], key) == 0) return false;
    if (s_vkWc3LoggedKeyCount < BZ_QUEST_VK_WC3_MAX_LOGGED_KEYS) {
        strncpy(s_vkWc3LoggedKeys[s_vkWc3LoggedKeyCount], key, sizeof(s_vkWc3LoggedKeys[0]) - 1);
        s_vkWc3LoggedKeyCount++;
    }
    return true;
}
#define VK_WC3_LOG_ONCE(identity, detail, ...)                                                       \
    do {                                                                                             \
        if (vk_wc3_log_once((identity), (detail))) fprintf(stderr, __VA_ARGS__);                     \
    } while (0)

/* Per-(render item, geoset) results of this frame's dynamic-material build,
 * consumed by draw_layer() via record_opaque()/record_blended() below.
 * paletteByteOffset is always a valid offset into vk3->paletteBuffer (slot 0
 * - the identity palette - for a static model, a no-active-sequence entity,
 * or a per-frame skinned-draw-budget overflow; see build_frame_dynamic_
 * material()'s doc comment). geosetAlpha defaults to 1.0 (no modulation)
 * under the same fallback conditions. Sized/indexed identically to
 * s_blendedDraws above: one slot per (item index, geoset index) pair. */
static VkDeviceSize s_paletteByteOffset[BZ_QUEST_WC3_MAX_RENDER_ITEMS][BZ_QUEST_WC3_MAX_GEOSETS_PER_MODEL];
static float s_geosetAlpha[BZ_QUEST_WC3_MAX_RENDER_ITEMS][BZ_QUEST_WC3_MAX_GEOSETS_PER_MODEL];

/* Pose-build scratch storage - too large for one stack frame (~2.6MB, see
 * bz_quest_wc3_render.h's bzQuestWc3Model_t scratch-buffer size rationale,
 * the same class of concern) - reused sequentially across items within one
 * frame (this function is single-threaded, one item at a time). */
static bzQuestWc3Node_t s_poseNodesScratch[BZ_QUEST_WC3_MAX_NODES_PER_MODEL];
static float s_poseNodeMatricesScratch[BZ_QUEST_WC3_MAX_NODES_PER_MODEL][16];
static float s_posePaletteScratch[BZ_QUEST_WC3_MAX_MATRIX_PALETTE][16];

/* Converts one arena-backed, real-key-count bzQuestWc3StoredTrack_t into the
 * pure module's fixed-size bzQuestWc3Track_t (see bz_quest_wc3_render.h's
 * bzQuestWc3StoredTrack_t doc comment on why these are two different
 * struct shapes for the same data). keyCount is clamped to
 * BZ_QUEST_WC3_MAX_KEYS_PER_TRACK as defense-in-depth; the ABI itself
 * already bounds every track to this same cap (see bz_quest_wc3_capture.c's
 * build_model_anim() sizing pass), so this is never expected to truncate
 * real data. */
static void convert_stored_track(const bzQuestWc3StoredTrack_t *stored, bzQuestWc3Track_t *out) {
    out->keyCount = stored->keyCount < BZ_QUEST_WC3_MAX_KEYS_PER_TRACK ? stored->keyCount
                                                                       : BZ_QUEST_WC3_MAX_KEYS_PER_TRACK;
    out->interp = stored->interp;
    out->globalSequence = stored->globalSequence;
    if (stored->vec3Keys)
        for (uint32_t k = 0; k < out->keyCount; k++) out->vec3Keys[k] = stored->vec3Keys[k];
    if (stored->quatKeys)
        for (uint32_t k = 0; k < out->keyCount; k++) out->quatKeys[k] = stored->quatKeys[k];
    if (stored->floatKeys)
        for (uint32_t k = 0; k < out->keyCount; k++) out->floatKeys[k] = stored->floatKeys[k];
}

/* Finds the sequence whose [startMsec,endMsec) contains frameMsec, mirroring
 * R_FindSequenceAtTime's own [start,end) contract exactly (see
 * bz_quest_wc3_render.h's bzQuestWc3StoredSeqRange_t doc comment). Returns
 * false (no active sequence) if none matches - callers must not call
 * bz_quest_wc3_build_pose() in that case (its own doc comment). */
static bool find_active_sequence(const bzQuestWc3ModelAnim_t *anim, uint32_t frameMsec,
                                 uint32_t *outStartMsec, uint32_t *outEndMsec) {
    for (uint32_t s = 0; s < anim->sequenceCount; s++) {
        if (frameMsec >= anim->sequences[s].startMsec && frameMsec < anim->sequences[s].endMsec) {
            *outStartMsec = anim->sequences[s].startMsec;
            *outEndMsec = anim->sequences[s].endMsec;
            return true;
        }
    }
    return false;
}

/* Looks up one track's global-sequence duration, treating an out-of-range
 * globalSequence index as BZ_QUEST_WC3_NO_GLOBAL_SEQUENCE's "0, unused"
 * placeholder (bz_quest_wc3_resolve_track_interval only reads this value
 * when track->globalSequence is itself in range, so an out-of-range index
 * never reaches this fallback in practice - defense-in-depth only, same
 * spirit as bz_quest_wc3_build_pose()'s own out-of-range handling). */
static uint32_t global_seq_duration_for_track(const bzQuestWc3ModelAnim_t *anim, uint32_t globalSequence) {
    if (globalSequence == BZ_QUEST_WC3_NO_GLOBAL_SEQUENCE || globalSequence >= anim->globalSeqDurationCount)
        return 0;
    return anim->globalSeqDurations[globalSequence];
}

/* The permanent identity-palette slot's byte offset (slot 0 - see
 * BZ_QUEST_VK_WC3_PALETTE_SLOT_COUNT's doc comment and
 * create_palette_resources()'s slot-0 write). */
static VkDeviceSize palette_identity_slot_offset(void) { return 0; }

/*
 * Computes this frame's authoritative per-(render item, geoset) bone
 * palette and geoset alpha, writing results into vk3->paletteMapped (skinned
 * slots 1..N) and s_paletteByteOffset/s_geosetAlpha (the lookup tables
 * record_opaque()/record_blended() read via draw_layer()). Must run once per
 * frame (not once per eye - see bz_quest_vk_wc3.h's paletteSlotsUsedThisFrame
 * doc comment), after the model cache upload pass so every resident model's
 * bzQuestWc3ModelAnim_t* is reachable via cache_find(). For each item's each
 * geoset:
 *   - model->meta.anim == NULL (genuinely static model, no MDX animation
 *     data at all - see bz_quest_wc3_capture.c's build_model_anim() "no
 *     tracks anywhere" early-out): identity slot, alpha 1.0.
 *   - No sequence contains item->frame (data/logic issue upstream - a valid
 *     entity should always have an active sequence, e.g. "stand"): logged
 *     once per model identity, identity slot, alpha 1.0 (bz_quest_wc3_
 *     build_pose() must not be called without a resolved sequence interval -
 *     its own doc comment - and sampling a real alpha track needs the same
 *     interval, so this is the one case where even a `hasAlphaTrack==false`
 *     geoset's otherwise-time-independent staticAlpha is skipped too, for a
 *     single consistent "no authoritative time available" fallback).
 *   - Skinned-draw budget (BZ_QUEST_VK_WC3_PALETTE_SLOT_COUNT - 1 slots)
 *     exceeded: logged once per model identity, identity slot (never a
 *     dropped/frozen draw - the geoset still draws, just unposed), real
 *     geoset alpha still applied (alpha sampling is not slot-bounded).
 */
static void build_frame_dynamic_material(bzQuestVkWc3_t *vk3, const bzQuestWc3RenderList_t *list) {
    vk3->paletteSlotsUsedThisFrame = 0;
    uint32_t renderClockMsec = bz_quest_wc3_render_clock_msec();

    for (uint32_t i = 0; i < list->count; i++) {
        const bzQuestWc3RenderItem_t *item = &list->items[i];
        void *modelHandle = cache_find(&vk3->modelCache, item->modelIdentity);
        if (!modelHandle) continue;
        const bzQuestVkWc3Model_t *model = (const bzQuestVkWc3Model_t *)modelHandle;
        const bzQuestWc3ModelAnim_t *anim = (const bzQuestWc3ModelAnim_t *)model->meta.anim;

        if (!anim) {
            for (uint32_t g = 0; g < model->meta.geosetCount; g++) {
                s_paletteByteOffset[i][g] = palette_identity_slot_offset();
                s_geosetAlpha[i][g] = 1.0f;
            }
            continue;
        }

        uint32_t seqStartMsec = 0, seqEndMsec = 0;
        bool haveSequence = find_active_sequence(anim, item->frame, &seqStartMsec, &seqEndMsec);
        if (!haveSequence) {
            VK_WC3_LOG_ONCE(item->modelIdentity, "no-active-sequence",
                            "bz_quest_vk_wc3: entity frame=%u matches no sequence in model '%s' - "
                            "drawing with identity pose\n",
                            item->frame, item->modelIdentity);
            for (uint32_t g = 0; g < model->meta.geosetCount; g++) {
                s_paletteByteOffset[i][g] = palette_identity_slot_offset();
                s_geosetAlpha[i][g] = 1.0f;
            }
            continue;
        }

        uint32_t nodeCount = anim->nodeCount < BZ_QUEST_WC3_MAX_NODES_PER_MODEL
                                 ? anim->nodeCount
                                 : BZ_QUEST_WC3_MAX_NODES_PER_MODEL;
        for (uint32_t n = 0; n < nodeCount; n++) {
            const bzQuestWc3StoredNode_t *sn = &anim->nodes[n];
            s_poseNodesScratch[n].parentIndex = sn->parentIndex;
            s_poseNodesScratch[n].pivot = sn->pivot;
            convert_stored_track(&sn->translation, &s_poseNodesScratch[n].translation);
            convert_stored_track(&sn->rotation, &s_poseNodesScratch[n].rotation);
            convert_stored_track(&sn->scale, &s_poseNodesScratch[n].scale);
        }
        bz_quest_wc3_build_pose(s_poseNodesScratch, nodeCount, seqStartMsec, seqEndMsec, item->frame,
                                renderClockMsec, anim->globalSeqDurations, anim->globalSeqDurationCount,
                                s_poseNodeMatricesScratch);

        for (uint32_t g = 0; g < model->meta.geosetCount; g++) {
            if (g >= anim->geosetAnimCount) {
                s_paletteByteOffset[i][g] = palette_identity_slot_offset();
                s_geosetAlpha[i][g] = 1.0f;
                continue;
            }
            const bzQuestWc3StoredGeosetAnim_t *ga = &anim->geosetAnims[g];

            float alpha = ga->staticAlpha;
            if (ga->hasAlphaTrack) {
                bzQuestWc3Track_t alphaTrack;
                convert_stored_track(&ga->alphaTrack, &alphaTrack);
                uint32_t gsd = global_seq_duration_for_track(anim, alphaTrack.globalSequence);
                uint32_t intervalStart, intervalEnd, sampleTime;
                bz_quest_wc3_resolve_track_interval(&alphaTrack, seqStartMsec, seqEndMsec, item->frame,
                                                    renderClockMsec, gsd, &intervalStart, &intervalEnd,
                                                    &sampleTime);
                bz_quest_wc3_sample_float_track(&alphaTrack, intervalStart, intervalEnd, sampleTime,
                                                ga->staticAlpha, &alpha);
            }
            s_geosetAlpha[i][g] = alpha;

            if (ga->paletteNodeIndexCount == 0) {
                s_paletteByteOffset[i][g] = palette_identity_slot_offset();
                continue;
            }
            if (vk3->paletteSlotsUsedThisFrame >= BZ_QUEST_VK_WC3_PALETTE_SLOT_COUNT - 1) {
                VK_WC3_LOG_ONCE(item->modelIdentity, "palette-budget-exceeded",
                                "bz_quest_vk_wc3: more than %u skinned draws in one frame - "
                                "some geosets will draw with an identity pose\n",
                                (uint32_t)(BZ_QUEST_VK_WC3_PALETTE_SLOT_COUNT - 1));
                s_paletteByteOffset[i][g] = palette_identity_slot_offset();
                continue;
            }
            uint32_t slot = 1 + vk3->paletteSlotsUsedThisFrame++;
            bz_quest_wc3_build_bone_palette(ga->paletteNodeIndices, ga->paletteNodeIndexCount,
                                            s_poseNodeMatricesScratch, nodeCount, s_posePaletteScratch);
            /* bz_quest_wc3_build_bone_palette() (like the rest of
             * bz_quest_wc3_anim.c) works entirely in raw MDX (Z-up) space -
             * see that module's own header comment. Vertex positions were
             * already converted to this project's target Y-up space back in
             * bz_quest_wc3_capture.c's decode_geoset_geometry(), so the
             * shader's `uBonePalette.bones[i] * pos4` multiply requires
             * Y-up matrices too, or animated translations/rotations land on
             * the wrong axes. Convert every slot (used and identity-padded
             * alike - the conversion maps identity to identity, see
             * bz_quest_wc3_convert_matrix_zup_to_yup()'s own doc comment)
             * before it ever reaches the mapped UBO. */
            for (uint32_t p = 0; p < BZ_QUEST_WC3_MAX_MATRIX_PALETTE; p++)
                bz_quest_wc3_convert_matrix_zup_to_yup(s_posePaletteScratch[p], s_posePaletteScratch[p]);
            VkDeviceSize byteOffset = (VkDeviceSize)slot * vk3->paletteSlotStride;
            memcpy((uint8_t *)vk3->paletteMapped + byteOffset, s_posePaletteScratch,
                  sizeof(float) * 16 * BZ_QUEST_WC3_MAX_MATRIX_PALETTE);
            s_paletteByteOffset[i][g] = byteOffset;
        }
    }
}

static void draw_layer(VkCommandBuffer cmd, bzQuestVkWc3_t *vk3, const bzQuestVkWc3Model_t *model,
                       const bzQuestWc3Geoset_t *geoset, const bzQuestWc3LayerDesc_t *layer,
                       const bzQuestWc3RenderItem_t *item, const float mvp[16],
                       VkDeviceSize paletteByteOffset, float geosetAlpha) {
    if (layer->unsupported) return; /* logged once already at capture time */
    /* Team-color/glow layers resolve their concrete texture from the DRAW's
     * own render item (per-entity, per-team_color), never the model's own
     * baked texture identity - see bzQuestWc3LayerDesc_t's teamColor/
     * teamGlow doc comment and bzQuestWc3RenderItem_t's teamColorTexture
     * Identity/teamGlowTextureIdentity doc comment. An empty identity here
     * means team-texture resolution failed for this entity this frame
     * (capture.c's BZ_TTA_RegisterTeamTexture() call site) - skip the draw,
     * do not fall back to an unrelated texture. */
    const char *textureIdentity = layer->textureIdentity;
    if (layer->teamColor) textureIdentity = item->teamColorTextureIdentity;
    else if (layer->teamGlow) textureIdentity = item->teamGlowTextureIdentity;
    if (textureIdentity[0] == '\0') return;
    void *texHandle = cache_find(&vk3->textureCache, textureIdentity);
    if (!texHandle) return; /* not yet uploaded - transient, picked up a future frame */
    const bzQuestVkWc3Texture_t *tex = (const bzQuestVkWc3Texture_t *)texHandle;

    bool twoSided = (layer->flags & (uint32_t)BZ_QUEST_MDX_GEO_TWOSIDED) != 0;
    bool noDepthTest = (layer->flags & (uint32_t)BZ_QUEST_MDX_GEO_NO_DEPTH_TEST) != 0;
    bool noDepthSet = (layer->flags & (uint32_t)BZ_QUEST_MDX_GEO_NO_DEPTH_SET) != 0;
    VkPipelineColorBlendAttachmentState blendUnused;
    bool depthWriteDefault = true;
    blend_state_for_mode(layer->blendMode, &blendUnused, &depthWriteDefault);
    bool depthWriteEnable = depthWriteDefault && !noDepthSet;
    VkPipeline pipeline = get_or_create_pipeline_variant(vk3, layer->blendMode, twoSided,
                                                        !noDepthTest, depthWriteEnable);
    if (pipeline == VK_NULL_HANDLE) return;

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);
    /* Set 0: this draw's texture (per-model/per-team-texture descriptor set,
     * unchanged from 5A). Set 1: the shared bone-palette buffer (one
     * descriptor set, reused every draw - see create_palette_resources()'s
     * doc comment), addressed by a per-draw dynamic offset - this is the
     * ONLY thing that varies per draw for this binding, so both sets are
     * bound together in one call with a single dynamic offset for set 1. */
    VkDescriptorSet sets[2] = {tex->descriptorSet, vk3->paletteDescriptorSet};
    uint32_t dynamicOffset = (uint32_t)paletteByteOffset;
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, vk3->pipelineLayout, 0, 2, sets, 1,
                           &dynamicOffset);
    VkDeviceSize offset = 0;
    vkCmdBindVertexBuffers(cmd, 0, 1, &model->vertexBuffer, &offset);
    vkCmdBindIndexBuffer(cmd, model->indexBuffer, 0, VK_INDEX_TYPE_UINT32);
    vkCmdPushConstants(cmd, vk3->pipelineLayout, VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(float) * 16,
                      mvp);
    /* alpha cutoff 0.5 only for BZ_TTA_BLEND_TRANSPARENT (alpha-key) - see
     * renderer/r_shader.c:308 and warcraft_vert.vert's push-constant doc
     * comment; 0.0 for every other blend mode never discards. Geoset alpha
     * (GEOA/KGAO) is folded into layer alpha here, CPU-side, matching
     * MDLX_EvaluateGeosetColor()/MDLX_EvaluateLayerAlpha()'s own
     * multiplicative combination (r_mdx_geoset.c) - no fragment shader
     * change needed. */
    float materialParams[4] = {layer->alpha * geosetAlpha,
                              layer->blendMode == BZ_QUEST_TTA_BLEND_TRANSPARENT ? 0.5f : 0.0f, 0.0f, 0.0f};
    vkCmdPushConstants(cmd, vk3->pipelineLayout, VK_SHADER_STAGE_FRAGMENT_BIT, sizeof(float) * 16,
                      sizeof(float) * 4, materialParams);
    vkCmdDrawIndexed(cmd, geoset->indexCount, 1, geoset->indexOffset, 0, 0);
}

void bz_quest_vk_wc3_record_opaque(bzQuestVkWc3_t *vk3, VkCommandBuffer cmd, const float viewProj[16],
                                   const float cameraWorldPos[3], const bzQuestWc3RenderList_t *list) {
    s_blendedDrawCount = 0;
    for (uint32_t i = 0; i < list->count; i++) {
        const bzQuestWc3RenderItem_t *item = &list->items[i];
        void *modelHandle = cache_find(&vk3->modelCache, item->modelIdentity);
        if (!modelHandle) continue;
        const bzQuestVkWc3Model_t *model = (const bzQuestVkWc3Model_t *)modelHandle;

        float mvp[16];
        bz_quest_mat4_multiply(viewProj, item->world, mvp);
        for (uint32_t g = 0; g < model->meta.geosetCount; g++) {
            const bzQuestWc3Geoset_t *geoset = &model->meta.geosets[g];
            for (uint32_t l = 0; l < geoset->layerCount; l++) {
                const bzQuestWc3LayerDesc_t *layer = &geoset->layers[l];
                if (layer->unsupported) continue;
                if (layer->blendMode < BZ_QUEST_TTA_BLEND_ALPHA) {
                    draw_layer(cmd, vk3, model, geoset, layer, item, mvp, s_paletteByteOffset[i][g],
                              s_geosetAlpha[i][g]);
                    continue;
                }
                if (s_blendedDrawCount >= sizeof(s_blendedDraws) / sizeof(s_blendedDraws[0])) continue;
                s_blendedDraws[s_blendedDrawCount].itemIndex = i;
                s_blendedDraws[s_blendedDrawCount].geosetIndex = g;
                s_blendedDraws[s_blendedDrawCount].layerIndex = l;
                s_blendedDraws[s_blendedDrawCount].distanceSq = distance_sq(item->world, cameraWorldPos);
                s_blendedDrawCount++;
            }
        }
    }
    if (s_blendedDrawCount > 1)
        qsort(s_blendedDraws, s_blendedDrawCount, sizeof(s_blendedDraws[0]),
              compare_blended_draw_farthest_first);
}

void bz_quest_vk_wc3_record_blended(bzQuestVkWc3_t *vk3, VkCommandBuffer cmd, const float viewProj[16],
                                    const bzQuestWc3RenderList_t *list) {
    for (uint32_t i = 0; i < s_blendedDrawCount; i++) {
        const BlendedDraw_t *bd = &s_blendedDraws[i];
        const bzQuestWc3RenderItem_t *item = &list->items[bd->itemIndex];
        void *modelHandle = cache_find(&vk3->modelCache, item->modelIdentity);
        if (!modelHandle) continue;
        const bzQuestVkWc3Model_t *model = (const bzQuestVkWc3Model_t *)modelHandle;
        const bzQuestWc3Geoset_t *geoset = &model->meta.geosets[bd->geosetIndex];
        const bzQuestWc3LayerDesc_t *layer = &geoset->layers[bd->layerIndex];
        float mvp[16];
        bz_quest_mat4_multiply(viewProj, item->world, mvp);
        draw_layer(cmd, vk3, model, geoset, layer, item, mvp, s_paletteByteOffset[bd->itemIndex][bd->geosetIndex],
                  s_geosetAlpha[bd->itemIndex][bd->geosetIndex]);
    }
}

bool bz_quest_vk_wc3_render_target(bzQuestVkWc3_t *vk3, uint32_t viewIndex, uint32_t imageIndex,
                                   uint32_t width, uint32_t height, const float viewProj[16],
                                   const float cameraWorldPos[3], const bzQuestWc3RenderList_t *list) {
    const bzQuestVk_t *vk = vk3->vk;
    if (viewIndex >= BZ_QUEST_VIEW_COUNT || imageIndex >= vk->targetCount[viewIndex]) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: render_target view=%u image=%u out of range", viewIndex,
                     imageIndex);
        return false;
    }
    const bzQuestVkTarget_t *target = &vk->targets[viewIndex][imageIndex];

    if (vkWaitForFences(vk->device, 1, &target->fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkWaitForFences failed");
        return false;
    }
    if (vkResetFences(vk->device, 1, &target->fence) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkResetFences failed");
        return false;
    }
    if (vkResetCommandBuffer(target->commandBuffer, 0) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkResetCommandBuffer failed");
        return false;
    }
    VkCommandBufferBeginInfo beginInfo = {0};
    beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    if (vkBeginCommandBuffer(target->commandBuffer, &beginInfo) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkBeginCommandBuffer failed");
        return false;
    }

    VkClearValue clearValues[2];
    clearValues[0].color.float32[0] = 0.0f;
    clearValues[0].color.float32[1] = 0.0f;
    clearValues[0].color.float32[2] = 0.0f;
    clearValues[0].color.float32[3] = 0.0f;
    clearValues[1].depthStencil.depth = 1.0f;
    clearValues[1].depthStencil.stencil = 0;
    VkRenderPassBeginInfo renderPassBeginInfo = {0};
    renderPassBeginInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
    renderPassBeginInfo.renderPass = vk->renderPass;
    renderPassBeginInfo.framebuffer = target->framebuffer;
    renderPassBeginInfo.renderArea.extent.width = width;
    renderPassBeginInfo.renderArea.extent.height = height;
    renderPassBeginInfo.clearValueCount = 2;
    renderPassBeginInfo.pClearValues = clearValues;
    vkCmdBeginRenderPass(target->commandBuffer, &renderPassBeginInfo, VK_SUBPASS_CONTENTS_INLINE);

    VkViewport viewport = {0.0f, 0.0f, (float)width, (float)height, 0.0f, 1.0f};
    vkCmdSetViewport(target->commandBuffer, 0, 1, &viewport);
    VkRect2D scissor = {{0, 0}, {width, height}};
    vkCmdSetScissor(target->commandBuffer, 0, 1, &scissor);

    /* Two-pass draw order: every OPAQUE/TRANSPARENT (alpha-tested) layer
     * first, then every genuinely-blended layer back-to-front by entity
     * distance to camera. Entity-level (not per-triangle) sorting is the
     * documented granularity limit - see docs/quest-tabletop.md. */
    bz_quest_vk_wc3_record_opaque(vk3, target->commandBuffer, viewProj, cameraWorldPos, list);
    bz_quest_vk_wc3_record_blended(vk3, target->commandBuffer, viewProj, list);

    vkCmdEndRenderPass(target->commandBuffer);
    if (vkEndCommandBuffer(target->commandBuffer) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkEndCommandBuffer failed");
        return false;
    }
    VkSubmitInfo submitInfo = {0};
    submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    submitInfo.commandBufferCount = 1;
    submitInfo.pCommandBuffers = &target->commandBuffer;
    if (vkQueueSubmit(vk->queue, 1, &submitInfo, target->fence) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: vkQueueSubmit failed");
        return false;
    }
    /* Same XR_KHR_vulkan_enable2 fence-wait-before-return contract as
     * bz_quest_vk_render_target() - see bz_quest_vk_wc3.h's top comment. */
    if (vkWaitForFences(vk->device, 1, &target->fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3: post-submit vkWaitForFences failed");
        return false;
    }
    return true;
}

void bz_quest_vk_wc3_destroy(bzQuestVkWc3_t *vk3) {
    if (vk3->vk && vk3->vk->device != VK_NULL_HANDLE) vkDeviceWaitIdle(vk3->vk->device);

    bz_quest_wc3_cache_shutdown(&vk3->modelCache);
    bz_quest_wc3_cache_shutdown(&vk3->textureCache);

    VkDevice device = vk3->vk ? vk3->vk->device : VK_NULL_HANDLE;
    if (device == VK_NULL_HANDLE) {
        memset(vk3, 0, sizeof(*vk3));
        return;
    }

    for (uint32_t i = 0; i < vk3->pipelineVariantCount; i++) {
        if (vk3->pipelineVariants[i].pipeline != VK_NULL_HANDLE)
            vkDestroyPipeline(device, vk3->pipelineVariants[i].pipeline, NULL);
    }
    if (vk3->uploadCommandBuffer != VK_NULL_HANDLE)
        vkFreeCommandBuffers(device, vk3->vk->commandPool, 1, &vk3->uploadCommandBuffer);
    if (vk3->stagingBuffer != VK_NULL_HANDLE) vkDestroyBuffer(device, vk3->stagingBuffer, NULL);
    if (vk3->stagingMemory != VK_NULL_HANDLE) vkFreeMemory(device, vk3->stagingMemory, NULL);
    if (vk3->pipelineLayout != VK_NULL_HANDLE) vkDestroyPipelineLayout(device, vk3->pipelineLayout, NULL);
    if (vk3->vertexShader != VK_NULL_HANDLE) vkDestroyShaderModule(device, vk3->vertexShader, NULL);
    if (vk3->fragmentShader != VK_NULL_HANDLE) vkDestroyShaderModule(device, vk3->fragmentShader, NULL);
    if (vk3->sampler != VK_NULL_HANDLE) vkDestroySampler(device, vk3->sampler, NULL);
    if (vk3->descriptorPool != VK_NULL_HANDLE) vkDestroyDescriptorPool(device, vk3->descriptorPool, NULL);
    if (vk3->descriptorSetLayout != VK_NULL_HANDLE)
        vkDestroyDescriptorSetLayout(device, vk3->descriptorSetLayout, NULL);
    /* Bone-palette resources (layer 5C) - reverse order of
     * create_palette_resources(): unmap before freeing memory, destroy the
     * buffer before the memory it's bound to, destroy the pool (which
     * implicitly frees paletteDescriptorSet) before the layout it was
     * allocated from. */
    if (vk3->paletteMapped) vkUnmapMemory(device, vk3->paletteMemory);
    if (vk3->paletteBuffer != VK_NULL_HANDLE) vkDestroyBuffer(device, vk3->paletteBuffer, NULL);
    if (vk3->paletteMemory != VK_NULL_HANDLE) vkFreeMemory(device, vk3->paletteMemory, NULL);
    if (vk3->paletteDescriptorPool != VK_NULL_HANDLE)
        vkDestroyDescriptorPool(device, vk3->paletteDescriptorPool, NULL);
    if (vk3->paletteDescriptorSetLayout != VK_NULL_HANDLE)
        vkDestroyDescriptorSetLayout(device, vk3->paletteDescriptorSetLayout, NULL);
    memset(vk3, 0, sizeof(*vk3));
}
