/*
 * bz_quest_vk.c - see bz_quest_vk.h for the module's responsibilities and
 * the XR_KHR_vulkan_enable2 synchronization contract that shapes
 * bz_quest_vk_render_target()'s fence-wait-before-return behavior.
 *
 * Every VkResult/XrResult this file checks is compared explicitly against
 * VK_SUCCESS/XR_SUCCESS - there is no "assume success" path, per AGENTS.md.
 */
#include "bz_quest_vk.h"

#include <stddef.h>
#include <stdlib.h>
#include <string.h>

#include "bz_quest_log.h"
#include "bz_quest_pure.h"
#include "bz_quest_scene.h"
#include "bz_quest_shaders_generated.h" /* generated by scripts/build-shaders.sh - see CMakeLists.txt */

static bool bz_quest_vk_find_memory_type(VkPhysicalDevice physicalDevice, uint32_t typeBits,
                                         VkMemoryPropertyFlags required, uint32_t *outIndex) {
    VkPhysicalDeviceMemoryProperties props;
    vkGetPhysicalDeviceMemoryProperties(physicalDevice, &props);
    for (uint32_t i = 0; i < props.memoryTypeCount; i++) {
        if (!(typeBits & (1u << i))) continue;
        if ((props.memoryTypes[i].propertyFlags & required) != required) continue;
        *outIndex = i;
        return true;
    }
    BZ_QUEST_LOGE("no memory type matches bits=0x%x flags=0x%x", typeBits,
                  (unsigned)required);
    return false;
}

static bool bz_quest_vk_select_depth_format(VkPhysicalDevice physicalDevice, VkFormat *outFormat) {
    /* Preference order: highest precision first; every candidate is
     * queried for VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT with
     * optimal tiling rather than assumed, since depth format support is not
     * guaranteed uniformly across Vulkan implementations (see the Vulkan
     * spec's "Required Format Support" table 47, which only guarantees
     * *one* of D32_SFLOAT/X8_D24_UNORM_PACK32 plus one of
     * D24_UNORM_S8_UINT/D32_SFLOAT_S8_UINT - never a single format
     * unconditionally). */
    static const VkFormat kCandidates[] = {VK_FORMAT_D32_SFLOAT, VK_FORMAT_D24_UNORM_S8_UINT,
                                            VK_FORMAT_D32_SFLOAT_S8_UINT, VK_FORMAT_D16_UNORM};
    for (size_t i = 0; i < sizeof(kCandidates) / sizeof(kCandidates[0]); i++) {
        VkFormatProperties props;
        vkGetPhysicalDeviceFormatProperties(physicalDevice, kCandidates[i], &props);
        if (props.optimalTilingFeatures & VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT) {
            *outFormat = kCandidates[i];
            return true;
        }
    }
    BZ_QUEST_LOGE("no depth-stencil-capable format found");
    return false;
}

bool bz_quest_vk_create_instance(const bzQuestXr_t *xr,
                                  const XrGraphicsRequirementsVulkanKHR *xrRequirements,
                                  bzQuestVk_t *vk) {
    memset(vk, 0, sizeof(*vk));

    uint32_t apiVersion = bz_quest_xr_version_to_vk_api_version(xrRequirements->minApiVersionSupported);

    VkApplicationInfo appInfo = {0};
    appInfo.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    appInfo.pApplicationName = "OpenRealmQuest";
    appInfo.applicationVersion = VK_MAKE_API_VERSION(0, 1, 0, 0);
    appInfo.pEngineName = "OpenRealm";
    appInfo.engineVersion = VK_MAKE_API_VERSION(0, 1, 0, 0);
    appInfo.apiVersion = apiVersion;

    VkInstanceCreateInfo instanceCreateInfo = {0};
    instanceCreateInfo.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    instanceCreateInfo.pApplicationInfo = &appInfo;
    /* No enabledExtensionNames/enabledLayerNames of our own -
     * XR_KHR_vulkan_enable2's xrCreateVulkanInstanceKHR merges in whatever
     * the runtime itself requires (see bz_quest_vk.h's top comment). */

    XrVulkanInstanceCreateInfoKHR createInfo = {0};
    createInfo.type = XR_TYPE_VULKAN_INSTANCE_CREATE_INFO_KHR;
    createInfo.systemId = xr->systemId;
    createInfo.pfnGetInstanceProcAddr = vkGetInstanceProcAddr;
    createInfo.vulkanCreateInfo = &instanceCreateInfo;
    createInfo.vulkanAllocator = NULL;

    VkResult vkResult = VK_SUCCESS;
    XrResult xrResult = xr->fns.createVulkanInstanceKHR(xr->instance, &createInfo, &vk->instance,
                                                         &vkResult);
    if (xrResult != XR_SUCCESS || vkResult != VK_SUCCESS) {
        BZ_QUEST_LOGE("xrCreateVulkanInstanceKHR failed: xr=%d vk=%d", xrResult,
                      vkResult);
        return false;
    }
    return true;
}

bool bz_quest_vk_create_device(const bzQuestXr_t *xr, bzQuestVk_t *vk) {
    XrVulkanGraphicsDeviceGetInfoKHR deviceGetInfo = {0};
    deviceGetInfo.type = XR_TYPE_VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR;
    deviceGetInfo.systemId = xr->systemId;
    deviceGetInfo.vulkanInstance = vk->instance;
    XrResult xrResult =
        xr->fns.getVulkanGraphicsDevice2KHR(xr->instance, &deviceGetInfo, &vk->physicalDevice);
    if (xrResult != XR_SUCCESS) {
        BZ_QUEST_LOGE("xrGetVulkanGraphicsDevice2KHR failed: %d", xrResult);
        return false;
    }

    uint32_t queueFamilyCount = 0;
    vkGetPhysicalDeviceQueueFamilyProperties(vk->physicalDevice, &queueFamilyCount, NULL);
    if (queueFamilyCount == 0) {
        BZ_QUEST_LOGE("device reports zero queue families");
        return false;
    }
    VkQueueFamilyProperties *queueFamilies =
        (VkQueueFamilyProperties *)malloc(sizeof(VkQueueFamilyProperties) * queueFamilyCount);
    if (!queueFamilies) {
        BZ_QUEST_LOGE("out of memory enumerating queue families");
        return false;
    }
    vkGetPhysicalDeviceQueueFamilyProperties(vk->physicalDevice, &queueFamilyCount, queueFamilies);
    int32_t graphicsFamily = -1;
    for (uint32_t i = 0; i < queueFamilyCount; i++) {
        if (queueFamilies[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) {
            graphicsFamily = (int32_t)i;
            break;
        }
    }
    free(queueFamilies);
    if (graphicsFamily < 0) {
        BZ_QUEST_LOGE("no VK_QUEUE_GRAPHICS_BIT queue family found");
        return false;
    }
    vk->queueFamilyIndex = (uint32_t)graphicsFamily;

    static const float kQueuePriority = 1.0f;
    VkDeviceQueueCreateInfo queueCreateInfo = {0};
    queueCreateInfo.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
    queueCreateInfo.queueFamilyIndex = vk->queueFamilyIndex;
    queueCreateInfo.queueCount = 1;
    queueCreateInfo.pQueuePriorities = &kQueuePriority;

    VkPhysicalDeviceFeatures features = {0}; /* fixed-function pipeline only; no features needed */
    VkDeviceCreateInfo deviceCreateInfo = {0};
    deviceCreateInfo.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
    deviceCreateInfo.queueCreateInfoCount = 1;
    deviceCreateInfo.pQueueCreateInfos = &queueCreateInfo;
    deviceCreateInfo.pEnabledFeatures = &features;
    /* No enabledExtensionNames of our own, same rationale as the instance:
     * xrCreateVulkanDeviceKHR merges in the runtime's required device
     * extensions itself. */

    XrVulkanDeviceCreateInfoKHR createInfo = {0};
    createInfo.type = XR_TYPE_VULKAN_DEVICE_CREATE_INFO_KHR;
    createInfo.systemId = xr->systemId;
    createInfo.pfnGetInstanceProcAddr = vkGetInstanceProcAddr;
    createInfo.vulkanPhysicalDevice = vk->physicalDevice;
    createInfo.vulkanCreateInfo = &deviceCreateInfo;
    createInfo.vulkanAllocator = NULL;

    VkResult vkResult = VK_SUCCESS;
    xrResult =
        xr->fns.createVulkanDeviceKHR(xr->instance, &createInfo, &vk->device, &vkResult);
    if (xrResult != XR_SUCCESS || vkResult != VK_SUCCESS) {
        BZ_QUEST_LOGE("xrCreateVulkanDeviceKHR failed: xr=%d vk=%d", xrResult,
                      vkResult);
        return false;
    }
    vkGetDeviceQueue(vk->device, vk->queueFamilyIndex, 0, &vk->queue);

    VkCommandPoolCreateInfo poolCreateInfo = {0};
    poolCreateInfo.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
    poolCreateInfo.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    poolCreateInfo.queueFamilyIndex = vk->queueFamilyIndex;
    if (vkCreateCommandPool(vk->device, &poolCreateInfo, NULL, &vk->commandPool) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkCreateCommandPool failed");
        return false;
    }
    return true;
}

static bool bz_quest_vk_create_render_pass(bzQuestVk_t *vk, VkFormat colorFormat) {
    VkAttachmentDescription attachments[2];
    memset(attachments, 0, sizeof(attachments));
    attachments[0].format = colorFormat;
    attachments[0].samples = VK_SAMPLE_COUNT_1_BIT;
    attachments[0].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    attachments[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
    attachments[0].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    attachments[0].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    attachments[0].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    /* Composited directly from this layout by the OpenXR runtime, matching
     * Khronos hello_xr's VulkanGraphicsPlugin convention (no PRESENT_SRC-
     * style layout applies to XR swapchain images - see
     * docs/quest-tabletop.md's "Vulkan/OpenXR quirks"). */
    attachments[0].finalLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

    attachments[1].format = vk->depthFormat;
    attachments[1].samples = VK_SAMPLE_COUNT_1_BIT;
    attachments[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    attachments[1].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    attachments[1].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    attachments[1].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    attachments[1].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    attachments[1].finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

    VkAttachmentReference colorRef = {0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
    VkAttachmentReference depthRef = {1, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};

    VkSubpassDescription subpass = {0};
    subpass.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
    subpass.colorAttachmentCount = 1;
    subpass.pColorAttachments = &colorRef;
    subpass.pDepthStencilAttachment = &depthRef;

    VkSubpassDependency dependency = {0};
    dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
    dependency.dstSubpass = 0;
    dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT |
                               VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
    dependency.dstStageMask = dependency.srcStageMask;
    dependency.srcAccessMask = 0;
    dependency.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
                                VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;

    VkRenderPassCreateInfo renderPassCreateInfo = {0};
    renderPassCreateInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
    renderPassCreateInfo.attachmentCount = 2;
    renderPassCreateInfo.pAttachments = attachments;
    renderPassCreateInfo.subpassCount = 1;
    renderPassCreateInfo.pSubpasses = &subpass;
    renderPassCreateInfo.dependencyCount = 1;
    renderPassCreateInfo.pDependencies = &dependency;

    if (vkCreateRenderPass(vk->device, &renderPassCreateInfo, NULL, &vk->renderPass) !=
        VK_SUCCESS) {
        BZ_QUEST_LOGE("vkCreateRenderPass failed");
        return false;
    }
    return true;
}

static bool bz_quest_vk_create_shader_module(VkDevice device, const unsigned char *code,
                                             uint32_t codeLen, VkShaderModule *outModule) {
    VkShaderModuleCreateInfo createInfo = {0};
    createInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    createInfo.codeSize = codeLen;
    createInfo.pCode = (const uint32_t *)code; /* generated header keeps 4-byte alignment */
    if (vkCreateShaderModule(device, &createInfo, NULL, outModule) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkCreateShaderModule failed");
        return false;
    }
    return true;
}

static bool bz_quest_vk_create_pipeline(bzQuestVk_t *vk) {
    if (!bz_quest_vk_create_shader_module(vk->device, g_bz_quest_tabletop_vert_spv,
                                          g_bz_quest_tabletop_vert_spv_len, &vk->vertexShader))
        return false;
    if (!bz_quest_vk_create_shader_module(vk->device, g_bz_quest_tabletop_frag_spv,
                                          g_bz_quest_tabletop_frag_spv_len, &vk->fragmentShader))
        return false;

    VkPipelineShaderStageCreateInfo stages[2];
    memset(stages, 0, sizeof(stages));
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vk->vertexShader;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = vk->fragmentShader;
    stages[1].pName = "main";

    VkVertexInputBindingDescription binding = {0, sizeof(bzQuestVertex_t),
                                                VK_VERTEX_INPUT_RATE_VERTEX};
    VkVertexInputAttributeDescription attrs[2] = {
        {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(bzQuestVertex_t, position)},
        {1, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(bzQuestVertex_t, color)},
    };
    VkPipelineVertexInputStateCreateInfo vertexInput = {0};
    vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vertexInput.vertexBindingDescriptionCount = 1;
    vertexInput.pVertexBindingDescriptions = &binding;
    vertexInput.vertexAttributeDescriptionCount = 2;
    vertexInput.pVertexAttributeDescriptions = attrs;

    VkPipelineInputAssemblyStateCreateInfo inputAssembly = {0};
    inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo viewportState = {0};
    viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewportState.viewportCount = 1;
    viewportState.scissorCount = 1;

    VkPipelineRasterizationStateCreateInfo rasterization = {0};
    rasterization.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rasterization.polygonMode = VK_POLYGON_MODE_FILL;
    /* CULL_MODE_NONE: see bz_quest_scene.c's top comment - the generated
     * test-scene geometry doesn't guarantee consistent winding per face, so
     * culling is deliberately not enabled for this prototype scene. */
    rasterization.cullMode = VK_CULL_MODE_NONE;
    rasterization.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rasterization.lineWidth = 1.0f;

    VkPipelineMultisampleStateCreateInfo multisample = {0};
    multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT; /* no MSAA - see docs/quest-tabletop.md */

    VkPipelineDepthStencilStateCreateInfo depthStencil = {0};
    depthStencil.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    depthStencil.depthTestEnable = VK_TRUE;
    depthStencil.depthWriteEnable = VK_TRUE;
    depthStencil.depthCompareOp = VK_COMPARE_OP_LESS;

    VkPipelineColorBlendAttachmentState blendAttachment = {0};
    blendAttachment.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                                      VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    blendAttachment.blendEnable = VK_FALSE; /* opaque geometry; alpha=1 written directly */

    VkPipelineColorBlendStateCreateInfo colorBlend = {0};
    colorBlend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    colorBlend.attachmentCount = 1;
    colorBlend.pAttachments = &blendAttachment;

    /* Viewport/scissor are dynamic because the two eyes' swapchains can
     * have different recommended image sizes per XrViewConfigurationView -
     * one pipeline is reused across both instead of building two. */
    static const VkDynamicState kDynamicStates[2] = {VK_DYNAMIC_STATE_VIEWPORT,
                                                      VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dynamicState = {0};
    dynamicState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamicState.dynamicStateCount = 2;
    dynamicState.pDynamicStates = kDynamicStates;

    VkPushConstantRange pushConstant = {VK_SHADER_STAGE_VERTEX_BIT, 0, sizeof(float) * 16};
    VkPipelineLayoutCreateInfo layoutCreateInfo = {0};
    layoutCreateInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutCreateInfo.pushConstantRangeCount = 1;
    layoutCreateInfo.pPushConstantRanges = &pushConstant;
    if (vkCreatePipelineLayout(vk->device, &layoutCreateInfo, NULL, &vk->pipelineLayout) !=
        VK_SUCCESS) {
        BZ_QUEST_LOGE("vkCreatePipelineLayout failed");
        return false;
    }

    VkGraphicsPipelineCreateInfo pipelineCreateInfo = {0};
    pipelineCreateInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pipelineCreateInfo.stageCount = 2;
    pipelineCreateInfo.pStages = stages;
    pipelineCreateInfo.pVertexInputState = &vertexInput;
    pipelineCreateInfo.pInputAssemblyState = &inputAssembly;
    pipelineCreateInfo.pViewportState = &viewportState;
    pipelineCreateInfo.pRasterizationState = &rasterization;
    pipelineCreateInfo.pMultisampleState = &multisample;
    pipelineCreateInfo.pDepthStencilState = &depthStencil;
    pipelineCreateInfo.pColorBlendState = &colorBlend;
    pipelineCreateInfo.pDynamicState = &dynamicState;
    pipelineCreateInfo.layout = vk->pipelineLayout;
    pipelineCreateInfo.renderPass = vk->renderPass;
    pipelineCreateInfo.subpass = 0;

    if (vkCreateGraphicsPipelines(vk->device, VK_NULL_HANDLE, 1, &pipelineCreateInfo, NULL,
                                  &vk->pipeline) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkCreateGraphicsPipelines failed");
        return false;
    }
    return true;
}

static bool bz_quest_vk_create_vertex_buffer(bzQuestVk_t *vk) {
    static bzQuestVertex_t verts[BZ_QUEST_SCENE_VERTEX_COUNT];
    /* Placeholder placement, not a gameplay convention: ~1m in front of and
     * ~0.5m below the XR_REFERENCE_SPACE_TYPE_LOCAL origin (approximate
     * headset height at startup) so the table sits at a plausible seated/
     * standing waist height. See docs/quest-tabletop.md. */
    if (!bz_quest_scene_generate(verts, 1.6f, -0.5f, 1.0f)) {
        BZ_QUEST_LOGE("bz_quest_scene_generate failed");
        return false;
    }
    vk->vertexCount = BZ_QUEST_SCENE_VERTEX_COUNT;

    VkDeviceSize bufferSize = sizeof(verts);
    VkBufferCreateInfo bufferCreateInfo = {0};
    bufferCreateInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bufferCreateInfo.size = bufferSize;
    bufferCreateInfo.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
    bufferCreateInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(vk->device, &bufferCreateInfo, NULL, &vk->vertexBuffer) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkCreateBuffer (vertex) failed");
        return false;
    }

    VkMemoryRequirements memReq;
    vkGetBufferMemoryRequirements(vk->device, vk->vertexBuffer, &memReq);
    uint32_t memoryTypeIndex = 0;
    /* Host-visible/coherent directly, no staging copy: this is a few
     * hundred vertices of static test-scene geometry, not a perf-sensitive
     * asset-streaming path (see bz_quest_vk.h's contract comment). */
    if (!bz_quest_vk_find_memory_type(vk->physicalDevice, memReq.memoryTypeBits,
                                      VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                          VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                                      &memoryTypeIndex))
        return false;

    VkMemoryAllocateInfo allocInfo = {0};
    allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.allocationSize = memReq.size;
    allocInfo.memoryTypeIndex = memoryTypeIndex;
    if (vkAllocateMemory(vk->device, &allocInfo, NULL, &vk->vertexBufferMemory) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkAllocateMemory (vertex) failed");
        return false;
    }
    if (vkBindBufferMemory(vk->device, vk->vertexBuffer, vk->vertexBufferMemory, 0) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkBindBufferMemory (vertex) failed");
        return false;
    }

    void *mapped = NULL;
    if (vkMapMemory(vk->device, vk->vertexBufferMemory, 0, bufferSize, 0, &mapped) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkMapMemory (vertex) failed");
        return false;
    }
    memcpy(mapped, verts, (size_t)bufferSize);
    vkUnmapMemory(vk->device, vk->vertexBufferMemory);
    return true;
}

bool bz_quest_vk_create_render_resources(bzQuestVk_t *vk, int64_t colorFormat) {
    if (!bz_quest_vk_select_depth_format(vk->physicalDevice, &vk->depthFormat)) return false;
    if (!bz_quest_vk_create_render_pass(vk, (VkFormat)colorFormat)) return false;
    if (!bz_quest_vk_create_pipeline(vk)) return false;
    if (!bz_quest_vk_create_vertex_buffer(vk)) return false;
    return true;
}

static bool bz_quest_vk_create_depth_target(bzQuestVk_t *vk, uint32_t width, uint32_t height,
                                           bzQuestVkTarget_t *target) {
    VkImageCreateInfo imageCreateInfo = {0};
    imageCreateInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    imageCreateInfo.imageType = VK_IMAGE_TYPE_2D;
    imageCreateInfo.format = vk->depthFormat;
    imageCreateInfo.extent.width = width;
    imageCreateInfo.extent.height = height;
    imageCreateInfo.extent.depth = 1;
    imageCreateInfo.mipLevels = 1;
    imageCreateInfo.arrayLayers = 1;
    imageCreateInfo.samples = VK_SAMPLE_COUNT_1_BIT;
    imageCreateInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
    imageCreateInfo.usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;
    imageCreateInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    imageCreateInfo.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(vk->device, &imageCreateInfo, NULL, &target->depthImage) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkCreateImage (depth) failed");
        return false;
    }

    VkMemoryRequirements memReq;
    vkGetImageMemoryRequirements(vk->device, target->depthImage, &memReq);
    uint32_t memoryTypeIndex = 0;
    if (!bz_quest_vk_find_memory_type(vk->physicalDevice, memReq.memoryTypeBits,
                                      VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, &memoryTypeIndex))
        return false;
    VkMemoryAllocateInfo allocInfo = {0};
    allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.allocationSize = memReq.size;
    allocInfo.memoryTypeIndex = memoryTypeIndex;
    if (vkAllocateMemory(vk->device, &allocInfo, NULL, &target->depthMemory) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkAllocateMemory (depth) failed");
        return false;
    }
    if (vkBindImageMemory(vk->device, target->depthImage, target->depthMemory, 0) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkBindImageMemory (depth) failed");
        return false;
    }

    VkImageViewCreateInfo viewCreateInfo = {0};
    viewCreateInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    viewCreateInfo.image = target->depthImage;
    viewCreateInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
    viewCreateInfo.format = vk->depthFormat;
    viewCreateInfo.subresourceRange.aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT;
    viewCreateInfo.subresourceRange.levelCount = 1;
    viewCreateInfo.subresourceRange.layerCount = 1;
    if (vkCreateImageView(vk->device, &viewCreateInfo, NULL, &target->depthView) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkCreateImageView (depth) failed");
        return false;
    }
    return true;
}

bool bz_quest_vk_create_targets(bzQuestVk_t *vk, uint32_t viewIndex,
                                 const bzQuestXrSwapchain_t *swapchain) {
    if (viewIndex >= BZ_QUEST_VIEW_COUNT) {
        BZ_QUEST_LOGE("viewIndex %u out of range", viewIndex);
        return false;
    }
    vk->targetCount[viewIndex] = swapchain->imageCount;
    for (uint32_t i = 0; i < swapchain->imageCount; i++) {
        bzQuestVkTarget_t *target = &vk->targets[viewIndex][i];
        memset(target, 0, sizeof(*target));

        VkImageViewCreateInfo colorViewCreateInfo = {0};
        colorViewCreateInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
        colorViewCreateInfo.image = swapchain->images[i];
        colorViewCreateInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
        colorViewCreateInfo.format = (VkFormat)swapchain->format;
        colorViewCreateInfo.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        colorViewCreateInfo.subresourceRange.levelCount = 1;
        colorViewCreateInfo.subresourceRange.layerCount = 1;
        if (vkCreateImageView(vk->device, &colorViewCreateInfo, NULL, &target->colorView) !=
            VK_SUCCESS) {
            BZ_QUEST_LOGE("vkCreateImageView (color) failed for view=%u image=%u",
                          viewIndex, i);
            return false;
        }

        if (!bz_quest_vk_create_depth_target(vk, swapchain->width, swapchain->height, target))
            return false;

        VkImageView attachments[2] = {target->colorView, target->depthView};
        VkFramebufferCreateInfo framebufferCreateInfo = {0};
        framebufferCreateInfo.sType = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;
        framebufferCreateInfo.renderPass = vk->renderPass;
        framebufferCreateInfo.attachmentCount = 2;
        framebufferCreateInfo.pAttachments = attachments;
        framebufferCreateInfo.width = swapchain->width;
        framebufferCreateInfo.height = swapchain->height;
        framebufferCreateInfo.layers = 1;
        if (vkCreateFramebuffer(vk->device, &framebufferCreateInfo, NULL, &target->framebuffer) !=
            VK_SUCCESS) {
            BZ_QUEST_LOGE("vkCreateFramebuffer failed for view=%u image=%u",
                          viewIndex, i);
            return false;
        }

        VkCommandBufferAllocateInfo cmdAllocInfo = {0};
        cmdAllocInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
        cmdAllocInfo.commandPool = vk->commandPool;
        cmdAllocInfo.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
        cmdAllocInfo.commandBufferCount = 1;
        if (vkAllocateCommandBuffers(vk->device, &cmdAllocInfo, &target->commandBuffer) !=
            VK_SUCCESS) {
            BZ_QUEST_LOGE("vkAllocateCommandBuffers failed for view=%u image=%u",
                          viewIndex, i);
            return false;
        }

        VkFenceCreateInfo fenceCreateInfo = {0};
        fenceCreateInfo.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
        fenceCreateInfo.flags = VK_FENCE_CREATE_SIGNALED_BIT; /* first wait must not block forever */
        if (vkCreateFence(vk->device, &fenceCreateInfo, NULL, &target->fence) != VK_SUCCESS) {
            BZ_QUEST_LOGE("vkCreateFence failed for view=%u image=%u", viewIndex,
                          i);
            return false;
        }
    }
    return true;
}

bool bz_quest_vk_render_target(bzQuestVk_t *vk, uint32_t viewIndex, uint32_t imageIndex,
                                uint32_t width, uint32_t height, const float mvp[16]) {
    if (viewIndex >= BZ_QUEST_VIEW_COUNT || imageIndex >= vk->targetCount[viewIndex]) {
        BZ_QUEST_LOGE("render_target: view=%u image=%u out of range", viewIndex,
                      imageIndex);
        return false;
    }
    bzQuestVkTarget_t *target = &vk->targets[viewIndex][imageIndex];

    if (vkWaitForFences(vk->device, 1, &target->fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkWaitForFences failed");
        return false;
    }
    if (vkResetFences(vk->device, 1, &target->fence) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkResetFences failed");
        return false;
    }

    if (vkResetCommandBuffer(target->commandBuffer, 0) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkResetCommandBuffer failed");
        return false;
    }
    VkCommandBufferBeginInfo beginInfo = {0};
    beginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    beginInfo.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    if (vkBeginCommandBuffer(target->commandBuffer, &beginInfo) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkBeginCommandBuffer failed");
        return false;
    }

    VkClearValue clearValues[2];
    /* Alpha 0 so untouched pixels show passthrough through (see
     * tabletop_frag.frag's top comment / XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND
     * compositing). */
    clearValues[0].color.float32[0] = 0.0f;
    clearValues[0].color.float32[1] = 0.0f;
    clearValues[0].color.float32[2] = 0.0f;
    clearValues[0].color.float32[3] = 0.0f;
    clearValues[1].depthStencil.depth = 1.0f;
    clearValues[1].depthStencil.stencil = 0;

    VkRenderPassBeginInfo renderPassBeginInfo = {0};
    renderPassBeginInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
    renderPassBeginInfo.renderPass = vk->renderPass;
    renderPassBeginInfo.framebuffer = target->framebuffer;
    renderPassBeginInfo.renderArea.extent.width = width;
    renderPassBeginInfo.renderArea.extent.height = height;
    renderPassBeginInfo.clearValueCount = 2;
    renderPassBeginInfo.pClearValues = clearValues;
    vkCmdBeginRenderPass(target->commandBuffer, &renderPassBeginInfo, VK_SUBPASS_CONTENTS_INLINE);

    vkCmdBindPipeline(target->commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, vk->pipeline);

    VkViewport viewport = {0.0f, 0.0f, (float)width, (float)height, 0.0f, 1.0f};
    vkCmdSetViewport(target->commandBuffer, 0, 1, &viewport);
    VkRect2D scissor = {{0, 0}, {width, height}};
    vkCmdSetScissor(target->commandBuffer, 0, 1, &scissor);

    vkCmdPushConstants(target->commandBuffer, vk->pipelineLayout, VK_SHADER_STAGE_VERTEX_BIT, 0,
                       sizeof(float) * 16, mvp);

    VkDeviceSize offset = 0;
    vkCmdBindVertexBuffers(target->commandBuffer, 0, 1, &vk->vertexBuffer, &offset);
    vkCmdDraw(target->commandBuffer, vk->vertexCount, 1, 0, 0);

    vkCmdEndRenderPass(target->commandBuffer);
    if (vkEndCommandBuffer(target->commandBuffer) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkEndCommandBuffer failed");
        return false;
    }

    VkSubmitInfo submitInfo = {0};
    submitInfo.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    submitInfo.commandBufferCount = 1;
    submitInfo.pCommandBuffers = &target->commandBuffer;
    if (vkQueueSubmit(vk->queue, 1, &submitInfo, target->fence) != VK_SUCCESS) {
        BZ_QUEST_LOGE("vkQueueSubmit failed");
        return false;
    }

    /* Block until this eye's rendering has actually completed before
     * returning: XR_KHR_vulkan_enable2 hands the runtime no semaphore/fence
     * to wait on itself, so the spec's "submitted rendering commands must
     * complete before the color image is used by xrEndFrame" requirement
     * has to be satisfied by the app blocking here (see bz_quest_vk.h's
     * contract comment and docs/quest-tabletop.md's "Current limitations"
     * for the CPU/GPU overlap this trades away). */
    if (vkWaitForFences(vk->device, 1, &target->fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) {
        BZ_QUEST_LOGE("post-submit vkWaitForFences failed");
        return false;
    }
    return true;
}

void bz_quest_vk_destroy(bzQuestVk_t *vk) {
    if (vk->device != VK_NULL_HANDLE) vkDeviceWaitIdle(vk->device);

    for (uint32_t v = 0; v < BZ_QUEST_VIEW_COUNT; v++) {
        for (uint32_t i = 0; i < vk->targetCount[v]; i++) {
            bzQuestVkTarget_t *target = &vk->targets[v][i];
            if (target->fence != VK_NULL_HANDLE) vkDestroyFence(vk->device, target->fence, NULL);
            if (target->commandBuffer != VK_NULL_HANDLE)
                vkFreeCommandBuffers(vk->device, vk->commandPool, 1, &target->commandBuffer);
            if (target->framebuffer != VK_NULL_HANDLE)
                vkDestroyFramebuffer(vk->device, target->framebuffer, NULL);
            if (target->depthView != VK_NULL_HANDLE)
                vkDestroyImageView(vk->device, target->depthView, NULL);
            if (target->depthImage != VK_NULL_HANDLE)
                vkDestroyImage(vk->device, target->depthImage, NULL);
            if (target->depthMemory != VK_NULL_HANDLE)
                vkFreeMemory(vk->device, target->depthMemory, NULL);
            if (target->colorView != VK_NULL_HANDLE)
                vkDestroyImageView(vk->device, target->colorView, NULL);
        }
        vk->targetCount[v] = 0;
    }

    if (vk->pipeline != VK_NULL_HANDLE) vkDestroyPipeline(vk->device, vk->pipeline, NULL);
    if (vk->pipelineLayout != VK_NULL_HANDLE)
        vkDestroyPipelineLayout(vk->device, vk->pipelineLayout, NULL);
    if (vk->vertexShader != VK_NULL_HANDLE) vkDestroyShaderModule(vk->device, vk->vertexShader, NULL);
    if (vk->fragmentShader != VK_NULL_HANDLE)
        vkDestroyShaderModule(vk->device, vk->fragmentShader, NULL);
    if (vk->renderPass != VK_NULL_HANDLE) vkDestroyRenderPass(vk->device, vk->renderPass, NULL);
    if (vk->vertexBuffer != VK_NULL_HANDLE) vkDestroyBuffer(vk->device, vk->vertexBuffer, NULL);
    if (vk->vertexBufferMemory != VK_NULL_HANDLE)
        vkFreeMemory(vk->device, vk->vertexBufferMemory, NULL);
    if (vk->commandPool != VK_NULL_HANDLE) vkDestroyCommandPool(vk->device, vk->commandPool, NULL);
    if (vk->device != VK_NULL_HANDLE) vkDestroyDevice(vk->device, NULL);
    if (vk->instance != VK_NULL_HANDLE) vkDestroyInstance(vk->instance, NULL);
    memset(vk, 0, sizeof(*vk));
}
