/*
 * bz_quest_vk_wc3_particles.c - see bz_quest_vk_wc3_particles.h.
 */
#include "bz_quest_vk_wc3_particles.h"

#include <stddef.h>
#include <string.h>

#include "bz_quest_log.h"
#include "bz_quest_shaders_generated.h" /* generated by scripts/build-shaders.sh - see CMakeLists.txt */

typedef struct {
    float viewProj[16];
    /* x = force-coverage-alpha-to-1 flag (High-severity reviewer fix, PR #28) - see
     * warcraft_particle_frag.frag's own doc comment; y/z/w unused (matches
     * warcraft_vert.vert's materialParams.z/w-unused convention). Fragment-stage-only, a
     * separate push range from viewProj - see bz_quest_vk_wc3_particles_create()'s doc comment. */
    float coverageParams[4];
} ParticlePushConsts_t;

static bool find_memory_type(VkPhysicalDevice physicalDevice, uint32_t typeBits,
                             VkMemoryPropertyFlags required, uint32_t *outIndex) {
    VkPhysicalDeviceMemoryProperties props;
    vkGetPhysicalDeviceMemoryProperties(physicalDevice, &props);
    for (uint32_t i = 0; i < props.memoryTypeCount; i++) {
        if (!(typeBits & (1u << i))) continue;
        if ((props.memoryTypes[i].propertyFlags & required) != required) continue;
        *outIndex = i;
        return true;
    }
    BZ_QUEST_LOGE("bz_quest_vk_wc3_particles: no memory type matches bits=0x%x flags=0x%x", typeBits,
                  (unsigned)required);
    return false;
}

static bool create_shader_module(VkDevice device, const uint32_t *code, uint32_t codeLen,
                                 VkShaderModule *out) {
    VkShaderModuleCreateInfo info = {0};
    info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    info.codeSize = codeLen;
    info.pCode = code;
    if (vkCreateShaderModule(device, &info, NULL, out) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3_particles: vkCreateShaderModule failed");
        return false;
    }
    return true;
}

/* One pipeline per blend mode - cull-none (a billboard has no meaningful winding) and depth-
 * test-on always, depth-write per bz_quest_vk_wc3_blend_state_for_mode()'s own default (no MDX
 * geoset flags apply to a particle emitter - see this file's header comment). */
static VkPipeline create_pipeline_variant(bzQuestVkWc3Particles_t *p, uint32_t blendMode) {
    VkPipelineShaderStageCreateInfo stages[2];
    memset(stages, 0, sizeof(stages));
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = p->vertexShader;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = p->fragmentShader;
    stages[1].pName = "main";

    VkVertexInputBindingDescription binding = {0, sizeof(bzQuestWc3ParticleVertex_t),
                                               VK_VERTEX_INPUT_RATE_VERTEX};
    /* Matches bzQuestWc3ParticleVertex_t field-for-field (bz_quest_wc3_particles.h) - UNORM8
     * attributes let the GPU divide by 255 automatically, so warcraft_particle_vert.vert reads
     * color/uv-rect/axis as already-normalized [0,1] floats with no shader-side scale. */
    VkVertexInputAttributeDescription attrs[5] = {
        {0, 0, VK_FORMAT_R32G32B32_SFLOAT, offsetof(bzQuestWc3ParticleVertex_t, posX)},
        {1, 0, VK_FORMAT_R8G8B8A8_UNORM, offsetof(bzQuestWc3ParticleVertex_t, color)},
        {2, 0, VK_FORMAT_R32_SFLOAT, offsetof(bzQuestWc3ParticleVertex_t, size)},
        {3, 0, VK_FORMAT_R8G8B8A8_UNORM, offsetof(bzQuestWc3ParticleVertex_t, u0)},
        {4, 0, VK_FORMAT_R8G8_UNORM, offsetof(bzQuestWc3ParticleVertex_t, axisX)},
    };
    VkPipelineVertexInputStateCreateInfo vertexInput = {0};
    vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vertexInput.vertexBindingDescriptionCount = 1;
    vertexInput.pVertexBindingDescriptions = &binding;
    vertexInput.vertexAttributeDescriptionCount = 5;
    vertexInput.pVertexAttributeDescriptions = attrs;

    VkPipelineInputAssemblyStateCreateInfo inputAssembly = {0};
    inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo viewportState = {0};
    viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewportState.viewportCount = 1;
    viewportState.scissorCount = 1;

    VkPipelineRasterizationStateCreateInfo rasterization = {0};
    rasterization.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rasterization.polygonMode = VK_POLYGON_MODE_FILL;
    rasterization.cullMode = VK_CULL_MODE_NONE;
    rasterization.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rasterization.lineWidth = 1.0f;

    VkPipelineMultisampleStateCreateInfo multisample = {0};
    multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineColorBlendAttachmentState blendAttachment;
    bool depthWriteDefault = true;
    bz_quest_vk_wc3_blend_state_for_mode(blendMode, &blendAttachment, &depthWriteDefault);

    VkPipelineDepthStencilStateCreateInfo depthStencil = {0};
    depthStencil.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    depthStencil.depthTestEnable = VK_TRUE;
    depthStencil.depthWriteEnable = depthWriteDefault ? VK_TRUE : VK_FALSE;
    depthStencil.depthCompareOp = VK_COMPARE_OP_LESS;

    VkPipelineColorBlendStateCreateInfo colorBlend = {0};
    colorBlend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    colorBlend.attachmentCount = 1;
    colorBlend.pAttachments = &blendAttachment;

    static const VkDynamicState kDynamicStates[2] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dynamicState = {0};
    dynamicState.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamicState.dynamicStateCount = 2;
    dynamicState.pDynamicStates = kDynamicStates;

    VkGraphicsPipelineCreateInfo info = {0};
    info.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    info.stageCount = 2;
    info.pStages = stages;
    info.pVertexInputState = &vertexInput;
    info.pInputAssemblyState = &inputAssembly;
    info.pViewportState = &viewportState;
    info.pRasterizationState = &rasterization;
    info.pMultisampleState = &multisample;
    info.pDepthStencilState = &depthStencil;
    info.pColorBlendState = &colorBlend;
    info.pDynamicState = &dynamicState;
    info.layout = p->pipelineLayout;
    info.renderPass = p->vk->renderPass;
    info.subpass = 0;

    VkPipeline pipeline = VK_NULL_HANDLE;
    if (vkCreateGraphicsPipelines(p->vk->device, VK_NULL_HANDLE, 1, &info, NULL, &pipeline) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3_particles: vkCreateGraphicsPipelines failed for blendMode=%u",
                      blendMode);
        return VK_NULL_HANDLE;
    }
    return pipeline;
}

/* Lazily creates/caches one pipeline per distinct blend mode encountered - mirrors
 * bz_quest_vk_wc3.c's own get_or_create_pipeline_variant() precedent exactly: called from the
 * per-eye record path, but a cache hit (the common case after the first frame that uses each of
 * the <=7 possible blend modes) is a fast bounded linear scan, never a per-frame vkCreate* call
 * once warmed up. */
static VkPipeline get_or_create_pipeline_variant(bzQuestVkWc3Particles_t *p, uint32_t blendMode) {
    for (uint32_t i = 0; i < p->pipelineVariantCount; i++) {
        if (p->pipelineVariants[i].blendMode == blendMode) return p->pipelineVariants[i].pipeline;
    }
    if (p->pipelineVariantCount >= BZ_QUEST_VK_WC3_PARTICLE_PIPELINE_VARIANTS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3_particles: pipeline variant cache exhausted (%u) - reusing variant 0",
                      (uint32_t)BZ_QUEST_VK_WC3_PARTICLE_PIPELINE_VARIANTS);
        return p->pipelineVariantCount > 0 ? p->pipelineVariants[0].pipeline : VK_NULL_HANDLE;
    }
    VkPipeline pipeline = create_pipeline_variant(p, blendMode);
    if (pipeline == VK_NULL_HANDLE) return VK_NULL_HANDLE;
    bzQuestVkWc3ParticlePipelineVariant_t *v = &p->pipelineVariants[p->pipelineVariantCount++];
    v->blendMode = blendMode;
    v->pipeline = pipeline;
    return pipeline;
}

bool bz_quest_vk_wc3_particles_create(const bzQuestVk_t *vk, const bzQuestVkWc3_t *vk3,
                                     bzQuestVkWc3Particles_t *out) {
    memset(out, 0, sizeof(*out));
    out->vk = vk;
    out->vk3 = vk3;

    if (!create_shader_module(vk->device, g_bz_quest_warcraft_particle_vert_spv,
                              g_bz_quest_warcraft_particle_vert_spv_len, &out->vertexShader) ||
        !create_shader_module(vk->device, g_bz_quest_warcraft_particle_frag_spv,
                              g_bz_quest_warcraft_particle_frag_spv_len, &out->fragmentShader))
        goto fail;

    /* Set 0: reuses vk3's OWN descriptor set layout (one combined-image-sampler at binding 0) -
     * see this file's header comment on why a second layout/pool/sampler is unnecessary. Two
     * push-constant ranges (mirrors bz_quest_vk_wc3.c's own model-layer split exactly): vertex-
     * stage viewProj at offset 0, fragment-stage coverageParams at offset 64 (the force-alpha-1
     * flag for BZ_QUEST_TTA_BLEND_OPAQUE/TRANSPARENT particle runs - see
     * warcraft_particle_frag.frag's doc comment). */
    VkPushConstantRange ranges[2];
    ranges[0].stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
    ranges[0].offset = 0;
    ranges[0].size = sizeof(float) * 16;
    ranges[1].stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
    ranges[1].offset = sizeof(float) * 16;
    ranges[1].size = sizeof(float) * 4;
    VkPipelineLayoutCreateInfo layoutInfo = {0};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = 1;
    layoutInfo.pSetLayouts = &vk3->descriptorSetLayout;
    layoutInfo.pushConstantRangeCount = 2;
    layoutInfo.pPushConstantRanges = ranges;
    if (vkCreatePipelineLayout(vk->device, &layoutInfo, NULL, &out->pipelineLayout) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3_particles: vkCreatePipelineLayout failed");
        goto fail;
    }

    /* Host-visible, persistently-mapped, rewritten every frame by
     * bz_quest_wc3_particles_pack() writing directly into `mapped` - see this file's header
     * comment; no separate host-side staging array (BZ_QUEST_VK_WC3_PARTICLE_MAX_VERTS *
     * sizeof(bzQuestWc3ParticleVertex_t) is tens of KB, too large for a comfortable stack
     * temporary, and would just be memcpy'd here right after anyway). */
    VkBufferCreateInfo bufferInfo = {0};
    bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bufferInfo.size = sizeof(bzQuestWc3ParticleVertex_t) * BZ_QUEST_VK_WC3_PARTICLE_MAX_VERTS;
    bufferInfo.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
    bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(vk->device, &bufferInfo, NULL, &out->vertexBuffer) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3_particles: vkCreateBuffer failed");
        goto fail;
    }
    VkMemoryRequirements memReq;
    vkGetBufferMemoryRequirements(vk->device, out->vertexBuffer, &memReq);
    uint32_t memType = 0;
    if (!find_memory_type(vk->physicalDevice, memReq.memoryTypeBits,
                          VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                          &memType))
        goto fail;
    VkMemoryAllocateInfo alloc = {0};
    alloc.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    alloc.allocationSize = memReq.size;
    alloc.memoryTypeIndex = memType;
    if (vkAllocateMemory(vk->device, &alloc, NULL, &out->vertexMemory) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3_particles: vkAllocateMemory failed");
        goto fail;
    }
    if (vkBindBufferMemory(vk->device, out->vertexBuffer, out->vertexMemory, 0) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3_particles: vkBindBufferMemory failed");
        goto fail;
    }
    if (vkMapMemory(vk->device, out->vertexMemory, 0, VK_WHOLE_SIZE, 0, &out->mapped) != VK_SUCCESS) {
        BZ_QUEST_LOGE("bz_quest_vk_wc3_particles: vkMapMemory failed");
        goto fail;
    }
    return true;

fail:
    bz_quest_vk_wc3_particles_destroy(out);
    return false;
}

void bz_quest_vk_wc3_particles_capture_and_upload(bzQuestVkWc3Particles_t *vkParticles) {
    vkParticles->runCount = 0;
    if (!vkParticles->mapped) return; /* create() failed - nothing to pack into */
    const bzQuestWc3ParticlePool_t *pool = bz_quest_vk_wc3_particle_pool(vkParticles->vk3);
    bz_quest_wc3_particles_pack(pool, (bzQuestWc3ParticleVertex_t *)vkParticles->mapped,
                                BZ_QUEST_VK_WC3_PARTICLE_MAX_VERTS, vkParticles->runs,
                                BZ_QUEST_WC3_MAX_PARTICLE_DRAW_RUNS, &vkParticles->runCount);
}

bool bz_quest_vk_wc3_particles_has_geometry(const bzQuestVkWc3Particles_t *vkParticles) {
    return vkParticles->runCount > 0;
}

void bz_quest_vk_wc3_particles_record(bzQuestVkWc3Particles_t *vkParticles, VkCommandBuffer cmd,
                                     const float viewProj[16]) {
    if (vkParticles->runCount == 0) return;
    VkDeviceSize offset = 0;
    vkCmdBindVertexBuffers(cmd, 0, 1, &vkParticles->vertexBuffer, &offset);
    ParticlePushConsts_t pc;
    memcpy(pc.viewProj, viewProj, sizeof(pc.viewProj));
    vkCmdPushConstants(cmd, vkParticles->pipelineLayout, VK_SHADER_STAGE_VERTEX_BIT, 0,
                      sizeof(pc.viewProj), pc.viewProj);
    for (uint32_t i = 0; i < vkParticles->runCount; i++) {
        const bzQuestWc3ParticleDrawRun_t *run = &vkParticles->runs[i];
        /* Miss = not yet resident this frame - transient, matches the model renderer's own "hit
         * path never triggers an upload, a miss just doesn't draw yet" contract (see this file's
         * header comment) - never a placeholder-textured draw. */
        const bzQuestVkWc3Texture_t *tex = bz_quest_vk_wc3_find_texture(vkParticles->vk3, run->textureIdentity);
        if (!tex) continue;
        VkPipeline pipeline = get_or_create_pipeline_variant(vkParticles, run->blendMode);
        if (pipeline == VK_NULL_HANDLE) continue;
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, vkParticles->pipelineLayout, 0, 1,
                               &tex->descriptorSet, 0, NULL);
        /* Force-coverage-alpha-to-1 flag (High-severity reviewer fix, PR #28) - true for
         * BZ_QUEST_TTA_BLEND_OPAQUE/TRANSPARENT runs (blendEnable=false: no blend equation runs at
         * all, this run's own shader alpha is written verbatim to the framebuffer) - see
         * warcraft_particle_frag.frag's doc comment. Only BZ_QUEST_TTA_BLEND_TRANSPARENT is reachable
         * from real PRE2 FilterMode data (see games/warcraft-3/docs/file-formats/mdx.md's
         * FilterMode mapping table - no raw value maps to OPAQUE), but this checks the actual
         * resolved blendEnable rather than assuming, matching bz_quest_vk_wc3.c's draw_layer()
         * own equivalent check exactly. */
        VkPipelineColorBlendAttachmentState blendState;
        bool depthWriteUnused = true;
        bz_quest_vk_wc3_blend_state_for_mode(run->blendMode, &blendState, &depthWriteUnused);
        pc.coverageParams[0] = blendState.blendEnable ? 0.0f : 1.0f;
        pc.coverageParams[1] = pc.coverageParams[2] = pc.coverageParams[3] = 0.0f;
        vkCmdPushConstants(cmd, vkParticles->pipelineLayout, VK_SHADER_STAGE_FRAGMENT_BIT,
                          sizeof(pc.viewProj), sizeof(pc.coverageParams), pc.coverageParams);
        vkCmdDraw(cmd, run->vertexCount, 1, run->firstVertex, 0);
    }
}

void bz_quest_vk_wc3_particles_destroy(bzQuestVkWc3Particles_t *vkParticles) {
    if (!vkParticles->vk) return;
    VkDevice device = vkParticles->vk->device;
    if (vkParticles->mapped) {
        vkUnmapMemory(device, vkParticles->vertexMemory);
        vkParticles->mapped = NULL;
    }
    if (vkParticles->vertexBuffer != VK_NULL_HANDLE) {
        vkDestroyBuffer(device, vkParticles->vertexBuffer, NULL);
        vkParticles->vertexBuffer = VK_NULL_HANDLE;
    }
    if (vkParticles->vertexMemory != VK_NULL_HANDLE) {
        vkFreeMemory(device, vkParticles->vertexMemory, NULL);
        vkParticles->vertexMemory = VK_NULL_HANDLE;
    }
    for (uint32_t i = 0; i < vkParticles->pipelineVariantCount; i++) {
        if (vkParticles->pipelineVariants[i].pipeline != VK_NULL_HANDLE)
            vkDestroyPipeline(device, vkParticles->pipelineVariants[i].pipeline, NULL);
    }
    vkParticles->pipelineVariantCount = 0;
    if (vkParticles->pipelineLayout != VK_NULL_HANDLE) {
        vkDestroyPipelineLayout(device, vkParticles->pipelineLayout, NULL);
        vkParticles->pipelineLayout = VK_NULL_HANDLE;
    }
    if (vkParticles->vertexShader != VK_NULL_HANDLE) {
        vkDestroyShaderModule(device, vkParticles->vertexShader, NULL);
        vkParticles->vertexShader = VK_NULL_HANDLE;
    }
    if (vkParticles->fragmentShader != VK_NULL_HANDLE) {
        vkDestroyShaderModule(device, vkParticles->fragmentShader, NULL);
        vkParticles->fragmentShader = VK_NULL_HANDLE;
    }
}
