/*
 * bin2c.c - tiny standalone host tool that turns a compiled SPIR-V binary
 * into a C byte-array header, so the layer-3 Vulkan renderer can embed its
 * shaders without depending on Android's AAssetManager (see
 * docs/quest-tabletop.md's "Shader build pipeline"). Deliberately a plain
 * host C program (built with `cc`, not the NDK) so
 * platform/android/quest/scripts/build-shaders.sh can run it on the build
 * machine during a normal CMake configure/build, matching this repo's
 * "commit source, not opaque binaries" rule for reproducible shader
 * compilation.
 *
 * Usage: bin2c <input.spv> <output.h> <array_name>
 */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: %s <input.spv> <output.h> <array_name>\n", argv[0]);
        return 1;
    }

    FILE *in = fopen(argv[1], "rb");
    if (!in) {
        fprintf(stderr, "bin2c: failed to open input '%s'\n", argv[1]);
        return 1;
    }
    fseek(in, 0, SEEK_END);
    long size = ftell(in);
    if (size < 0 || (size % 4) != 0) {
        fprintf(stderr, "bin2c: '%s' is not a valid SPIR-V binary (size=%ld not a multiple of 4)\n",
                argv[1], size);
        fclose(in);
        return 1;
    }
    fseek(in, 0, SEEK_SET);

    unsigned char *data = (unsigned char *)malloc((size_t)size);
    if (!data) {
        fprintf(stderr, "bin2c: out of memory reading '%s'\n", argv[1]);
        fclose(in);
        return 1;
    }
    if (fread(data, 1, (size_t)size, in) != (size_t)size) {
        fprintf(stderr, "bin2c: short read on '%s'\n", argv[1]);
        fclose(in);
        free(data);
        return 1;
    }
    fclose(in);

    /* SPIR-V magic number, little- or big-endian encoded, per the SPIR-V
     * spec section 2.3 "Physical Layout of a SPIR-V Module and Instruction" -
     * https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#PhysicalLayout */
    if (size < 4 ||
        !((data[0] == 0x03 && data[1] == 0x02 && data[2] == 0x23 && data[3] == 0x07) ||
          (data[3] == 0x03 && data[2] == 0x02 && data[1] == 0x23 && data[0] == 0x07))) {
        fprintf(stderr, "bin2c: '%s' does not start with the SPIR-V magic number - refusing to embed\n",
                argv[1]);
        free(data);
        return 1;
    }

    FILE *out = fopen(argv[2], "w");
    if (!out) {
        fprintf(stderr, "bin2c: failed to open output '%s'\n", argv[2]);
        free(data);
        return 1;
    }
    fprintf(out, "/* Generated by platform/android/quest/scripts/bin2c.c from %s - do not edit. */\n",
            argv[1]);
    fprintf(out, "static const unsigned char %s[] = {\n", argv[3]);
    for (long i = 0; i < size; i++) {
        fprintf(out, "0x%02x,%s", data[i], ((i + 1) % 16 == 0) ? "\n" : " ");
    }
    fprintf(out, "\n};\n");
    fprintf(out, "static const unsigned int %s_len = %ldu;\n", argv[3], size);
    fclose(out);
    free(data);
    return 0;
}
