#!/bin/sh
# platform/android/quest/scripts/build-shaders.sh
#
# Deterministic, from-source shader build: compiles every GLSL source in
# platform/android/quest/app/src/main/cpp/shaders/*.{vert,frag} to SPIR-V
# with the NDK's glslc, verifies each output starts with the SPIR-V magic
# number, and embeds it as an aligned C uint32_t word array via bin2c.c so bz_quest_vk.c can
# #include the result without any Android AAssetManager plumbing (see
# docs/quest-tabletop.md's "Shader build pipeline"). CMakeLists.txt invokes
# this script as a custom_command so every `gradle assembleDebug`/`cmake
# --build` regenerates the header from source - no SPIR-V binary is ever
# committed to the repo, only this script's *inputs* (the .vert/.frag
# files) and its own logic.
#
# Also runnable standalone for manual verification:
#   platform/android/quest/scripts/build-shaders.sh <output-dir>
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../../../.." && pwd)
SHADER_SRC_DIR="$ROOT/platform/android/quest/app/src/main/cpp/shaders"
OUT_DIR=${1:-"$SHADER_SRC_DIR/.generated"}
mkdir -p "$OUT_DIR"

if [ -z "${ANDROID_NDK_HOME:-}" ]; then
    if [ -n "${ANDROID_HOME:-}" ] && [ -d "$ANDROID_HOME/ndk" ]; then
        ANDROID_NDK_HOME=$(find "$ANDROID_HOME/ndk" -mindepth 1 -maxdepth 1 -type d | sort -V | tail -n1)
    elif [ -d "$HOME/Library/Android/sdk/ndk" ]; then
        ANDROID_NDK_HOME=$(find "$HOME/Library/Android/sdk/ndk" -mindepth 1 -maxdepth 1 -type d | sort -V | tail -n1)
    fi
fi
if [ -z "${ANDROID_NDK_HOME:-}" ] || [ ! -d "$ANDROID_NDK_HOME" ]; then
    echo "build-shaders.sh: could not resolve an installed NDK (set ANDROID_NDK_HOME)" >&2
    exit 1
fi

HOST_TAG=darwin-x86_64
case "$(uname -s)" in
    Linux) HOST_TAG=linux-x86_64 ;;
esac
GLSLC="$ANDROID_NDK_HOME/shader-tools/$HOST_TAG/glslc"
if [ ! -x "$GLSLC" ]; then
    echo "build-shaders.sh: missing NDK glslc at $GLSLC" >&2
    exit 1
fi

BIN2C="$OUT_DIR/bin2c"
CC=${CC:-cc}
"$CC" -std=c11 -O2 -o "$BIN2C" "$SCRIPT_DIR/bin2c.c"

# --- Compile each source and embed it -------------------------------------
compile_one() {
    NAME=$1  # e.g. "tabletop_vert" - also the generated array's name suffix
    STAGE=$2
    EXT=$3
    SRC="$SHADER_SRC_DIR/$NAME.$EXT"
    SPV="$OUT_DIR/$NAME.spv"
    HDR="$OUT_DIR/$NAME.spv.h"
    if [ ! -f "$SRC" ]; then
        echo "build-shaders.sh: missing shader source $SRC" >&2
        exit 1
    fi
    "$GLSLC" --target-env=vulkan1.0 -fshader-stage="$STAGE" -O -o "$SPV" "$SRC"
    "$BIN2C" "$SPV" "$HDR" "g_bz_quest_${NAME}_spv"
    echo "compiled $SRC -> $SPV -> $HDR"
}

compile_one tabletop_vert vertex vert
compile_one tabletop_frag fragment frag
compile_one warcraft_vert vertex vert
compile_one warcraft_frag fragment frag

# --- Umbrella header the CMake build/renderer #includes -------------------
GEN_HEADER="$OUT_DIR/bz_quest_shaders_generated.h"
{
    echo "/* Generated by platform/android/quest/scripts/build-shaders.sh - do not edit. */"
    echo "#ifndef BZ_QUEST_SHADERS_GENERATED_H"
    echo "#define BZ_QUEST_SHADERS_GENERATED_H"
    cat "$OUT_DIR/tabletop_vert.spv.h"
    cat "$OUT_DIR/tabletop_frag.spv.h"
    cat "$OUT_DIR/warcraft_vert.spv.h"
    cat "$OUT_DIR/warcraft_frag.spv.h"
    echo "#endif /* BZ_QUEST_SHADERS_GENERATED_H */"
} > "$GEN_HEADER"

echo "wrote $GEN_HEADER"
